package org.example.project.plots

import org.example.project.plotsFormat.Characters.*
import org.example.project.plotsFormat.PlotTree

val WymBondScene = PlotTree.plotTree {
	entry("wym-bond-1")
	normal("wym-bond-1", NARRATION, "那天的课结束得很晚。窗外的合肥已经亮起一片灯，吴一鸣却没有像往常一样第一个收拾书包。", "wym-bond-2")
	normal("wym-bond-2", WYJ, "还不回家吗？", "wym-bond-3")
	normal("wym-bond-3", WYM, "年糕今天生病了。妈妈说不用担心，可是我还是想早点回去。", "wym-bond-4")
	normal("wym-bond-4", WYJ, "那就回去吧。今天的题不用补。", "wym-bond-4a")
	normal("wym-bond-4a", NARRATION, "她背起书包，却没有走。手指绕着书包带子，白色的睫毛垂下来，像是在心里把那道题又读了一遍。窗外的灯，一盏一盏亮得更密了。", "wym-bond-5")
	normal("wym-bond-5", WYM, "可是我还差一道。", "wym-bond-6")
	normal("wym-bond-6", WYJ, "一道题不会决定你今天有没有努力。", "wym-bond-7")
	normal("wym-bond-7", WYM, "老师，你是不是觉得我很慢？", "wym-bond-8")
	normal("wym-bond-8", NARRATION, "她的语气很轻，像是在问一道已经知道答案、却仍然不敢提交的问题。", "wym-bond-9")
	normal("wym-bond-9", WYJ, "我觉得你需要比别人更多一点时间。这个事实不等于你不够好。", "wym-bond-10")
	normal("wym-bond-10", WYM, "可是比赛不会因为我需要时间就等我。", "wym-bond-11")
	normal("wym-bond-11", WYJ, "是。赛场不会等任何人。所以我们要练习的不是让你变成别人，而是让你在自己的速度里，尽可能走得远。", "wym-bond-12")
	normal("wym-bond-12", WYM, "我有时候很羡慕李佳迪。她看一眼就会，我要看好多遍。", "wym-bond-13")
	normal("wym-bond-13", WYJ, "你看到的是她看一眼就会，没看到她为了那一眼准备了多久。", "wym-bond-14")
	normal("wym-bond-14", WYM, "那我准备很久，也可以吗？", "wym-bond-15")
	normal("wym-bond-15", WYJ, "当然可以。", "wym-bond-16")
	normal("wym-bond-16", WYM, "如果最后还是没有她厉害呢？", "wym-bond-17")
	normal("wym-bond-17", WYJ, "那也不影响你成为你自己。你不是来复制她的。", "wym-bond-18")
	normal("wym-bond-18", NARRATION, "吴一鸣低头摸了摸书包上的小猫挂件。白色长发垂下来，遮住了她的眼睛。", "wym-bond-19")
	normal("wym-bond-19", WYM, "老师，如果有一天我真的考得很差，你还会让我继续来吗？", "wym-bond-20")
	normal("wym-bond-20", WYJ, "只要你还想来。", "wym-bond-21")
	normal("wym-bond-21", WYM, "不是因为我有希望拿奖？", "wym-bond-22")
	normal("wym-bond-22", WYJ, "不是。因为你是吴一鸣。成绩是你做过的事情，不是你这个人。", "wym-bond-23")
	normal("wym-bond-23", WYM, "那我今天先回去看年糕。明天再把这道题想完。", "wym-bond-24")
	normal("wym-bond-24", WYJ, "好。明天再想。", "wym-bond-25")
	normal("wym-bond-25", NARRATION, "她走到门口时停了一下：老师，谢谢你总是知道我什么时候是真的困，什么时候只是害怕。你没有回答，只看着她跑进夜色里。", "wym-bond-26")
	normal("wym-bond-26", NARRATION, "门关上以后，你走到她刚才的座位，把那道没做完的题在草稿纸上默默演算了一遍，然后在旁边写下一行只有自己看得懂的小提示，留到下周给她。你并不急着回宿舍——今晚泡面可以晚一点吃。", null)
}

val LznBondScene = PlotTree.plotTree {
	entry("lzn-bond-1")
	normal("lzn-bond-1", NARRATION, "刘子诺把一张排名表折了四次，折痕正好穿过她自己的名字。", "lzn-bond-2")
	normal("lzn-bond-2", LZN, "我这次又没有超过李佳迪。", "lzn-bond-3")
	normal("lzn-bond-3", WYJ, "你想超过她，还是想变得更强？", "lzn-bond-4")
	normal("lzn-bond-4", LZN, "有什么区别？", "lzn-bond-5")
	normal("lzn-bond-5", WYJ, "前者会让她的名字一直在你前面。后者会让你知道自己每周比上周多会了什么。", "lzn-bond-6")
	normal("lzn-bond-6", LZN, "可是我就是会在意。她第一的时候，我会不舒服；我第一的时候，又怕只是她这次状态不好。", "lzn-bond-7")
	normal("lzn-bond-7", WYJ, "你不是在和李佳迪比赛，你是在和一个想象中的自己比赛。那个自己永远不会失误，永远不会紧张，永远不会输。", "lzn-bond-8")
	normal("lzn-bond-8", LZN, "那种自己不存在。", "lzn-bond-9")
	normal("lzn-bond-9", WYJ, "所以你不需要赢过她。你需要允许真实的自己存在。", "lzn-bond-10")
	normal("lzn-bond-10", NARRATION, "刘子诺把排名表展开，又慢慢抚平。黄色的灯光落在她被橡皮擦得发白的字迹上。", "lzn-bond-11")
	normal("lzn-bond-11", LZN, "我其实很怕大家觉得我只是吵。好像我一说话，就说明我不会。", "lzn-bond-12")
	normal("lzn-bond-12", WYJ, "说话多不是缺点。没有经过检查的结论才是。", "lzn-bond-13")
	normal("lzn-bond-13", LZN, "你每次都能把批评说得像作业要求。", "lzn-bond-14")
	normal("lzn-bond-14", WYJ, "因为你不是需要被哄着才能进步的人。", "lzn-bond-15")
	normal("lzn-bond-15", LZN, "那我能不能有一次只被哄，不被分析？", "lzn-bond-16")
	normal("lzn-bond-16", WYJ, "可以。你这次已经做得很好了。", "lzn-bond-17")
	normal("lzn-bond-17", LZN, "就一句？", "lzn-bond-18")
	normal("lzn-bond-18", WYJ, "你希望我说几句？", "lzn-bond-19")
	normal("lzn-bond-19", LZN, "至少说到我相信为止。", "lzn-bond-20")
	normal("lzn-bond-20", WYJ, "你这次在最紧张的时候停下来检查了三遍，最后一道题虽然没有做完，却没有把前面的答案全部改错。你已经比过去更可靠了。", "lzn-bond-21")
	normal("lzn-bond-21", LZN, "……我好像真的变可靠了一点。", "lzn-bond-22")
	normal("lzn-bond-22", WYJ, "不是好像。", "lzn-bond-23")
	normal("lzn-bond-23", LZN, "那我以后还会输很多次吗？", "lzn-bond-24")
	normal("lzn-bond-24", WYJ, "会。", "lzn-bond-25")
	normal("lzn-bond-25", LZN, "老师，你安慰人的方式真的很差。", "lzn-bond-26")
	normal("lzn-bond-26", WYJ, "但我会在你输的时候提醒你，你曾经赢过自己。", "lzn-bond-27")
	normal("lzn-bond-27", NARRATION, "刘子诺终于把那张排名表收进书包。她没有撕掉，也没有再看一眼。", "lzn-bond-28")
	normal("lzn-bond-28", NARRATION, "她跑下楼后，你才发现自己也曾折过一模一样的排名表。你把桌上被她敲乱的几支笔重新码齐，忽然想给以前的教练发条消息，问一句‘你当年是不是也这样看着我’。想了想，还是没发。", null)
}

val ZhcBondScene = PlotTree.plotTree {
	entry("zhc-bond-1")
	normal("zhc-bond-1", NARRATION, "朱皓辰留到最后。教室里只剩下键盘的余光，以及她摊开的第二本错题本。", "zhc-bond-2")
	normal("zhc-bond-2", WYJ, "今天怎么不回去？", "zhc-bond-3")
	normal("zhc-bond-3", ZHC, "我想问一个问题。", "zhc-bond-4")
	normal("zhc-bond-4", WYJ, "你问。", "zhc-bond-5")
	normal("zhc-bond-5", ZHC, "如果我一直都很稳定，但永远不是最强的那一个，这算不算失败？", "zhc-bond-6")
	normal("zhc-bond-6", WYJ, "你为什么觉得‘不是最强’就等于失败？", "zhc-bond-7")
	normal("zhc-bond-7", ZHC, "因为大家最后都会记住第一名。", "zhc-bond-8")
	normal("zhc-bond-8", WYJ, "大家是谁？", "zhc-bond-9")
	normal("zhc-bond-9", ZHC, "家里的人，学校里的人，比赛名单上的人。", "zhc-bond-10")
	normal("zhc-bond-10", WYJ, "他们记得第一名，不代表第二名、第三名的路就没有意义。", "zhc-bond-11")
	normal("zhc-bond-11", ZHC, "可我有时候也想被看见。", "zhc-bond-12")
	normal("zhc-bond-12", NARRATION, "她说得很慢，每个字都像从心里搬到桌面上。", "zhc-bond-13")
	normal("zhc-bond-13", ZHC, "我不想永远只是‘那个很稳的人’。我也想有一次，让别人因为我做到了什么而惊讶。", "zhc-bond-14")
	normal("zhc-bond-14", WYJ, "那就去争取。稳定不是你的终点，只是你可以放心挑战更高难度的底气。", "zhc-bond-15")
	normal("zhc-bond-15", ZHC, "如果挑战失败呢？", "zhc-bond-16")
	normal("zhc-bond-16", WYJ, "把失败记进错题本。", "zhc-bond-17")
	normal("zhc-bond-17", ZHC, "你总是这么回答。", "zhc-bond-18")
	normal("zhc-bond-18", WYJ, "因为我到现在也没有更好的答案。", "zhc-bond-19")
	normal("zhc-bond-19", ZHC, "你拿过 NOI Ag，也拿过 ICPC Final Au。", "zhc-bond-20")
	normal("zhc-bond-20", WYJ, "所以我更知道那些奖项不能替我回答所有问题。它们只能证明某一天、某一场比赛，我做对了足够多的题。", "zhc-bond-21")
	normal("zhc-bond-21", ZHC, "那你为什么还愿意教我们？", "zhc-bond-22")
	normal("zhc-bond-22", WYJ, "因为我曾经也希望有人在我输了以后，告诉我不必立刻变回一个完美的人。", "zhc-bond-23")
	normal("zhc-bond-23", ZHC, "现在有人告诉我了。", "zhc-bond-24")
	normal("zhc-bond-24", WYJ, "嗯。", "zhc-bond-25")
	normal("zhc-bond-25", ZHC, "谢谢。", "zhc-bond-26")
	normal("zhc-bond-26", NARRATION, "朱皓辰合上错题本，在扉页又添了一句话：今天主动问了问题。那不是错误，却值得记录。", "zhc-bond-27")
	normal("zhc-bond-27", NARRATION, "她离开后，教室安静得只剩键盘的余光。你没有急着关灯，而是翻开自己大学的笔记本，在最后一页也添了一行：今天有个学生，学会了先问出口。你盯着那行字看了很久，像在确认自己也还没有停止学习。", null)
}

val LjdBondScene = PlotTree.plotTree {
	entry("ljd-bond-1")
	normal("ljd-bond-1", NARRATION, "李佳迪把一份解题报告放在你面前，页边密密麻麻全是红色批注。", "ljd-bond-2")
	normal("ljd-bond-2", LJD, "请你指出最致命的问题。", "ljd-bond-3")
	normal("ljd-bond-3", WYJ, "你已经指出了。", "ljd-bond-4")
	normal("ljd-bond-4", LJD, "我想听你说。", "ljd-bond-5")
	normal("ljd-bond-5", WYJ, "最致命的问题是，你写这份报告不是为了理解，而是为了证明自己不会错。", "ljd-bond-6")
	normal("ljd-bond-6", NARRATION, "她的手指停在纸面上。冷淡的表情第一次出现了明显的裂痕。", "ljd-bond-7")
	normal("ljd-bond-7", LJD, "不会错不好吗？", "ljd-bond-8")
	normal("ljd-bond-8", WYJ, "好。但不可能。", "ljd-bond-9")
	normal("ljd-bond-9", LJD, "我不喜欢这个答案。", "ljd-bond-10")
	normal("ljd-bond-10", WYJ, "我也不喜欢。但你越早知道自己会错，越不会把一次错误当成世界末日。", "ljd-bond-11")
	normal("ljd-bond-11", LJD, "如果我不是第一名，别人就会觉得我没有那么聪明。", "ljd-bond-12")
	normal("ljd-bond-12", WYJ, "别人怎么想，不是你能优化的变量。", "ljd-bond-13")
	normal("ljd-bond-13", LJD, "你总是把这种事说得像算法。", "ljd-bond-14")
	normal("ljd-bond-14", WYJ, "因为我不擅长说得温柔。", "ljd-bond-15")
	normal("ljd-bond-15", LJD, "你也会担心别人超过你吗？", "ljd-bond-16")
	normal("ljd-bond-16", WYJ, "会。我甚至会因为这种担心变得不像自己。", "ljd-bond-17")
	normal("ljd-bond-17", LJD, "你拿到 ICPC Final Au 之后也会？", "ljd-bond-18")
	normal("ljd-bond-18", WYJ, "奖项只能让别人更确定地称赞你，不能让你更确定地相信自己。下一场比赛开始，所有人还是会重新比较。", "ljd-bond-19")
	normal("ljd-bond-19", LJD, "那你是怎么继续的？", "ljd-bond-20")
	normal("ljd-bond-20", WYJ, "我没有一直继续。有些时候我停下来，承认自己很累，很怕输，也承认我不想把一生都交给一块计分板。", "ljd-bond-21")
	normal("ljd-bond-21", LJD, "可你还是回来了。", "ljd-bond-22")
	normal("ljd-bond-22", WYJ, "因为停下来以后，我仍然喜欢问题本身。不是喜欢成为第一，而是喜欢在没有答案的时候，找到答案。", "ljd-bond-23")
	normal("ljd-bond-23", LJD, "我想试着把这两件事分开。", "ljd-bond-24")
	normal("ljd-bond-24", WYJ, "这是比再做十道题更难的训练。", "ljd-bond-24a")
	normal("ljd-bond-24a", NARRATION, "李佳迪没有立刻回答。她的手指在那份报告的边缘慢慢收拢，又松开，像是在掂量‘分开’这两个字到底有多重。", "ljd-bond-25")
	normal("ljd-bond-25", LJD, "那我会练。", "ljd-bond-26")
	normal("ljd-bond-26", NARRATION, "她拿回那份报告，划掉了标题里‘最优解’三个字，重新写下：一次诚实的尝试。", "ljd-bond-27")
	normal("ljd-bond-27", NARRATION, "她走后，你把那份被红笔改了又改的报告翻到最后一页，在页脚轻轻写下一句没打算给她看的话：你不必永远正确，只要愿意继续诚实。写完，你把它夹进了自己的备课本里。", null)
}

// ---- 好感 8：信任加深、第一次把心里的软处交出来的场景 ----

val WymFavor8Scene = PlotTree.plotTree {
	entry("wym-f8-1")
	normal("wym-f8-1", NARRATION, "又是一个傍晚。吴一鸣抱着年糕的照片靠在窗边，你走过去时，她已经半睡半醒。", "wym-f8-2")
	normal("wym-f8-2", WYM, "老师……我是不是又睡着了。", "wym-f8-3")
	normal("wym-f8-3", WYJ, "只是打了个盹。你剩两道题没写，我帮你标好了。", "wym-f8-4")
	normal("wym-f8-4", WYM, "你怎么知道我卡在哪两道？", "wym-f8-5")
	normal("wym-f8-5", WYJ, "你困之前，笔尖一直停在那两页上。", "wym-f8-6")
	normal("wym-f8-6", NARRATION, "她愣了一下，红色的瞳孔慢慢清醒过来，脸上是一种被认真看待的、有些不知所措的神情。", "wym-f8-7")
	normal("wym-f8-7", WYM, "其实我最近晚上睡得很少。我想在困之前多做几道，让你觉得我没有偷懒。", "wym-f8-8")
	normal("wym-f8-8", WYJ, "我从没觉得你偷懒。困不是偷懒，是你身体在提醒你该休息了。", "wym-f8-9")
	normal("wym-f8-9", WYM, "可是别人一天能做十道，我做三道就撑不住了。", "wym-f8-10")
	normal("wym-f8-10", WYJ, "那你就把这三道做到真的懂。慢，不等于差。", "wym-f8-11")
	normal("wym-f8-11", WYM, "老师，有你在的时候，我好像就没那么容易困了。", "wym-f8-12")
	normal("wym-f8-12", NARRATION, "她说完这句，自己先红了耳朵，赶紧低下头假装去看那两道被标好的题。", "wym-f8-13")
	normal("wym-f8-13", WYJ, "那以后卡住了，就先叫我，别硬撑到睡着。", "wym-f8-14")
	normal("wym-f8-14", WYM, "嗯。我答应你。", "wym-f8-15")
	normal("wym-f8-15", NARRATION, "那天她把两道题都做完了，一次也没有睡着。走的时候，她把年糕的照片留在了你桌上，说明天再来取。", null)
}

val LznFavor8Scene = PlotTree.plotTree {
	entry("lzn-f8-1")
	normal("lzn-f8-1", NARRATION, "刘子诺把一张新的排名表拍在桌上，动作很大，脸上却没有从前那种患得患失。", "lzn-f8-2")
	normal("lzn-f8-2", LZN, "老师你看！这次我没有冲到第一，但我超过了上一次的自己！", "lzn-f8-3")
	normal("lzn-f8-3", WYJ, "我看到了。而且你这次没有先去看别人的名次。", "lzn-f8-4")
	normal("lzn-f8-4", LZN, "被你发现了。以前我拿到排名，第一眼一定是找李佳迪在哪。", "lzn-f8-5")
	normal("lzn-f8-5", LZN, "这次我先找了自己。原来我一直在进步，只是从前都被‘输给别人’盖住了。", "lzn-f8-6")
	normal("lzn-f8-6", WYJ, "这是很重要的一步。你终于把标尺换成了自己。", "lzn-f8-7")
	normal("lzn-f8-7", LZN, "其实我以前特别怕你失望。我一失误，就觉得对不起你花的时间。", "lzn-f8-8")
	normal("lzn-f8-8", WYJ, "我从来不会因为一次失误就失望。我在意的是你有没有从失误里学到东西。", "lzn-f8-9")
	normal("lzn-f8-9", LZN, "那……你有没有为我骄傲过？", "lzn-f8-10")
	normal("lzn-f8-10", NARRATION, "她问得很快，问完又有点后悔，粉色的短发下露出一双紧张的眼睛。", "lzn-f8-11")
	normal("lzn-f8-11", WYJ, "有。就在刚才，你先找自己名字的那一刻。", "lzn-f8-12")
	normal("lzn-f8-12", LZN, "……那我要把这张排名表收好。这是第一张我不是因为名次、而是因为进步留下来的表。", "lzn-f8-13")
	normal("lzn-f8-13", NARRATION, "她小心地把排名表夹进笔记本，像收藏一枚只有自己看得懂的奖牌。", null)
}

val ZhcFavor8Scene = PlotTree.plotTree {
	entry("zhc-f8-1")
	normal("zhc-f8-1", NARRATION, "课程结束后，朱皓辰把一本整理好的资料放到你桌上。封面没有名字，只有四个字：给王老师。", "zhc-f8-2")
	normal("zhc-f8-2", WYJ, "这是……", "zhc-f8-3")
	normal("zhc-f8-3", ZHC, "我把这半年大家最常错的题分了类，也写了我自己的讲法。方便你下周备课。", "zhc-f8-4")
	normal("zhc-f8-4", NARRATION, "你翻开资料，字迹一如既往地工整。每一类错误后面，都附着一句她自己的注解。", "zhc-f8-5")
	normal("zhc-f8-5", WYJ, "你花了很多时间吧。", "zhc-f8-6")
	normal("zhc-f8-6", ZHC, "还好。我只是……想为这个班做点什么。", "zhc-f8-7")
	normal("zhc-f8-7", ZHC, "以前我总觉得自己只是‘那个很稳的人’，除了不出错，好像没什么存在感。", "zhc-f8-8")
	normal("zhc-f8-8", WYJ, "可这本资料里，全是只有你才写得出的东西。这不是‘不出错’，这是创造。", "zhc-f8-9")
	normal("zhc-f8-9", NARRATION, "朱皓辰沉默了几秒。她一向不擅长回应这样的话。", "zhc-f8-10")
	normal("zhc-f8-10", ZHC, "那……你会用它吗？", "zhc-f8-11")
	normal("zhc-f8-11", WYJ, "会。而且我会告诉她们，这是朱皓辰写的。", "zhc-f8-12")
	normal("zhc-f8-12", ZHC, "不用署名也可以。", "zhc-f8-13")
	normal("zhc-f8-13", WYJ, "该署的名，就要署。你做的事，值得被看见。", "zhc-f8-14")
	normal("zhc-f8-14", NARRATION, "她没有再拒绝。第二天上课，当你说出‘这是朱皓辰整理的’时，她低着头，耳根却悄悄红了。", null)
}

val LjdFavor8Scene = PlotTree.plotTree {
	entry("ljd-f8-1")
	normal("ljd-f8-1", NARRATION, "李佳迪把自己的解题报告发给你，请你指出其中的问题。这已经是这周第二次。", "ljd-f8-2")
	normal("ljd-f8-2", LJD, "你昨天说的那处边界，我想了很久。", "ljd-f8-3")
	normal("ljd-f8-3", WYJ, "想通了？", "ljd-f8-4")
	normal("ljd-f8-4", LJD, "想通了。但我想通的不只是那道题。", "ljd-f8-5")
	normal("ljd-f8-5", WYJ, "还想通了什么？", "ljd-f8-6")
	normal("ljd-f8-6", LJD, "我发现，我把报告发给你，不完全是为了让你挑错。", "ljd-f8-7")
	normal("ljd-f8-7", NARRATION, "她说到这里停了一下。蓝色的瞳孔里，那种惯常的锋利淡了一些。", "ljd-f8-8")
	normal("ljd-f8-8", LJD, "是因为，你指出的问题，从来不会让我觉得‘我很蠢’。你只说这一步可以更好，不说我不行。", "ljd-f8-9")
	normal("ljd-f8-9", WYJ, "因为你确实不蠢。指出问题，是为了让强的人更强，不是为了证明谁弱。", "ljd-f8-10")
	normal("ljd-f8-10", LJD, "我从小到大，很少有人敢这样对我说话。他们要么怕我，要么捧我。", "ljd-f8-11")
	normal("ljd-f8-11", WYJ, "我既不怕你，也不打算捧你。我只想让你走得更远。", "ljd-f8-12")
	normal("ljd-f8-12", LJD, "……这句话，我会记很久。", "ljd-f8-13")
	normal("ljd-f8-13", NARRATION, "她合上电脑，没有像往常一样立刻起身。那天她多留了一会儿，只是安静地坐着，看你把她的报告认真看完。", null)
}

// ---- 好感 10：恋爱阈值之前的中段深化场景 ----

val WymMidBondScene = PlotTree.plotTree {
	entry("wym-mid-1")
	normal("wym-mid-1", NARRATION, "训练结束后，吴一鸣没有急着走。她把手机屏幕转过来给你看——年糕蜷在她的旧校服上睡着了。", "wym-mid-2")
	normal("wym-mid-2", WYM, "老师，你有没有发现，我最近好像没那么容易困了。", "wym-mid-3")
	normal("wym-mid-3", WYJ, "我发现了。你上周那道题，是在没有人提醒的情况下自己做完的。", "wym-mid-4")
	normal("wym-mid-4", WYM, "因为我想让你看到，我不是只会睡觉的那个人。", "wym-mid-5")
	normal("wym-mid-5", NARRATION, "她说完自己先愣了一下，红色的瞳孔在灯下显得格外认真。", "wym-mid-6")
	normal("wym-mid-6", WYJ, "我从来没有把你当成只会睡觉的人。", "wym-mid-7")
	normal("wym-mid-7", WYM, "我知道。可我还是想亲耳听你说。", "wym-mid-8")
	normal("wym-mid-8", WYM, "老师，等这一切都结束了，你还会记得我吗？不是记得‘那个总是困的学生’，是记得我。", "wym-mid-9")
	normal("wym-mid-9", WYJ, "会。我会记得你在每一次快要放弃的时候，还是选择了醒过来。", "wym-mid-10")
	normal("wym-mid-10", NARRATION, "吴一鸣笑了。她把手机收好，轻声说了句‘那就好’，像是把一件担心了很久的事终于放下。", null)
}

val LznMidBondScene = PlotTree.plotTree {
	entry("lzn-mid-1")
	normal("lzn-mid-1", NARRATION, "刘子诺这次没有带排名表。她只是搬了张椅子，坐到你对面。", "lzn-mid-2")
	normal("lzn-mid-2", LZN, "老师，我今天不是来复盘的。", "lzn-mid-3")
	normal("lzn-mid-3", WYJ, "那是来做什么？", "lzn-mid-4")
	normal("lzn-mid-4", LZN, "来谢谢你。以前我一紧张就说个不停，现在我知道那是害怕。是你让我第一次觉得，害怕也没关系。", "lzn-mid-5")
	normal("lzn-mid-5", WYJ, "是你自己愿意去看那份害怕。我只是没有替你把它藏起来。", "lzn-mid-6")
	normal("lzn-mid-6", LZN, "你知道吗，我现在最想赢的比赛，是让你觉得‘教我没有白费’。", "lzn-mid-7")
	normal("lzn-mid-7", WYJ, "这句话本身，就已经说明没有白费。", "lzn-mid-8")
	normal("lzn-mid-8", NARRATION, "刘子诺难得安静了几秒。她低头，粉色的短发挡住了表情。", "lzn-mid-9")
	normal("lzn-mid-9", LZN, "……老师，我好像不只是想赢给你看。", "lzn-mid-10")
	normal("lzn-mid-10", NARRATION, "她没有把那句话说完，站起来把椅子搬回原位，却在门口回头笑了一下，比任何一次拿到第一都亮。", null)
}

val ZhcMidBondScene = PlotTree.plotTree {
	entry("zhc-mid-0a")
	// —— 先是四个人的群体互动，再慢慢收束到朱皓辰一个人 ——
	normal("zhc-mid-0a", NARRATION, "那天的训练结束得早。四个人没急着走，围在一起复盘上周的模拟赛，教室里难得地热闹。", "zhc-mid-0b")
	normal("zhc-mid-0b", LZN, "我跟你们说，那道题我最后十分钟才想明白，差点没交上！", "zhc-mid-0c")
	normal("zhc-mid-0c", WYM, "我那道……年糕踩了我键盘，我就顺势交了个半成品。", "zhc-mid-0d")
	normal("zhc-mid-0d", LJD, "所以你的分是年糕帮你拿的。", "zhc-mid-0e")
	normal("zhc-mid-0e", NARRATION, "笑声里，只有朱皓辰没怎么说话。她把大家随口提到的每一个坑，都安静地记进了错题本。", "zhc-mid-0f")
	normal("zhc-mid-0f", LZN, "皓辰你怎么又在记？该走啦，我妈在楼下等我。", "zhc-mid-0g")
	normal("zhc-mid-0g", ZHC, "你们先走。我再坐一会儿。", "zhc-mid-0h")
	normal("zhc-mid-0h", NARRATION, "三个人的脚步声消失在楼道尽头。热闹退去，教室重新安静下来，只剩你和她。她却没有像往常那样立刻收拾书包。", "zhc-mid-1")
	normal("zhc-mid-1", NARRATION, "朱皓辰把第二本错题本翻到最后一页。那一页没有题，只有一行小字。", "zhc-mid-2")
	normal("zhc-mid-2", ZHC, "老师，你能看看这一页吗？", "zhc-mid-3")
	normal("zhc-mid-3", NARRATION, "你凑近看去，那行字写着：今天我没有等别人开口，先说了自己的想法。", "zhc-mid-4")
	normal("zhc-mid-4", WYJ, "这是很了不起的一页。", "zhc-mid-5")
	normal("zhc-mid-5", ZHC, "我以前觉得，安静是最安全的。被看见反而危险。", "zhc-mid-6")
	normal("zhc-mid-6", ZHC, "可是这一年，我好像不那么想被藏起来了。至少，不想被你藏起来。", "zhc-mid-7")
	normal("zhc-mid-7", WYJ, "我一直看得见你。哪怕你不说话，我也看得见。", "zhc-mid-8")
	normal("zhc-mid-8", NARRATION, "朱皓辰的手指在那行字上停了很久。她的表情没有太大变化，眼眶却慢慢红了。", "zhc-mid-9")
	normal("zhc-mid-9", ZHC, "谢谢你，一直看得见。", "zhc-mid-10")
	normal("zhc-mid-10", NARRATION, "她合上错题本，把它抱在怀里，像抱着某种终于敢承认的东西。", null)
}

val LjdMidBondScene = PlotTree.plotTree {
	entry("ljd-mid-1")
	normal("ljd-mid-1", NARRATION, "李佳迪破天荒地迟到了。她走进来时，手里没有拿任何题。", "ljd-mid-2")
	normal("ljd-mid-2", LJD, "我今天没有准备问题。", "ljd-mid-3")
	normal("ljd-mid-3", WYJ, "那你想聊什么？", "ljd-mid-4")
	normal("ljd-mid-4", LJD, "我想问一件和算法无关的事。你会不会觉得，我这个人除了聪明，没有别的地方值得别人靠近？", "ljd-mid-5")
	normal("ljd-mid-5", WYJ, "不会。你会在朱皓辰讲不下去的时候等她，会把空调调高一度再说不是为自己。这些都不是‘聪明’。", "ljd-mid-6")
	normal("ljd-mid-6", NARRATION, "李佳迪蓝色的瞳孔里第一次露出一点无措。她一向擅长回答问题，却不擅长被这样回答。", "ljd-mid-7")
	normal("ljd-mid-7", LJD, "你观察得很仔细。", "ljd-mid-8")
	normal("ljd-mid-8", WYJ, "因为你值得被仔细地看。", "ljd-mid-9")
	normal("ljd-mid-9", LJD, "……这句话，比你给我讲过的任何一道题都难反驳。", "ljd-mid-10")
	normal("ljd-mid-10", NARRATION, "她没有再说什么，只是把椅子往你这边挪近了一点，安静地坐了很久。窗外，合肥的天色一点点暗下来。", null)
}

