package org.example.project.plots

import org.example.project.plotsFormat.Characters.*
import org.example.project.plotsFormat.PlotTree

val CspScene = PlotTree.plotTree {
	entry("csp-1")
	normal("csp-1", NARRATION, "成绩公布那天，合肥下着很细的雨。你站在教室门口，手机上的名单迟迟没有点开。", "csp-2")
	normal("csp-2", WYJ, "我先说清楚一件事。无论结果怎样，今天都不补题，不加训，也不追问谁考得不好。", "csp-3")
	normal("csp-3", LZN, "老师，你说得像我们已经全军覆没了一样。快点看吧，我已经紧张到想把手机吃了。", "csp-4")
	normal("csp-4", WYM, "唔……如果没过的话，是不是就不用继续早起了？", "csp-5")
	normal("csp-5", ZHC, "吴一鸣，你平时也没有早起。", "csp-6")
	normal("csp-6", WYM, "所以才问。", "csp-7")
	normal("csp-7", LJD, "王老师，直接看结果。逃避不会改变分数。", "csp-8")
	normal("csp-8", NARRATION, "你点开名单。四个名字排在一起，像四枚被雨水打湿、却没有散开的墨点。", "csp-9")
	normal("csp-9", LZN, "都……都在！我们四个都过了！", "csp-10")
	normal("csp-10", NARRATION, "刘子诺先是笑，笑声很快变成了哭声。她抬起手想擦眼睛，又嫌自己哭得太丢人，只好把脸埋进胳膊里。", "csp-11")
	normal("csp-11", LZN, "我这次没有冲到最高分，也没有超过李佳迪。但是我没有在最后十分钟乱改代码。老师，我真的做到了。", "csp-12")
	normal("csp-12", WYJ, "嗯。你赢的不是排名，是那个明知道害怕，仍然按计划做完检查的自己。", "csp-13")
	normal("csp-13", WYM, "我的分数……比我想的高。年糕知道了会不会觉得我很厉害？", "csp-14")
	normal("csp-14", WYJ, "它大概只会踩你的键盘。", "csp-15")
	normal("csp-15", WYM, "那也算祝贺。", "csp-16")
	normal("csp-16", ZHC, "我有一道题用了很久。最后能做出来，不是因为突然想到了，而是因为没有放弃检查每一个条件。", "csp-17")
	normal("csp-17", WYJ, "这就是稳定的意义。不是每一次都领先，而是别人开始慌乱时，你还知道下一步该做什么。", "csp-18")
	normal("csp-18", LJD, "我的成绩不够好。", "csp-19")
	normal("csp-19", LZN, "你这句话放在我们这里是不是有点过分？", "csp-20")
	normal("csp-20", LJD, "我不是说排名。我在最后一道题上花了太多时间。如果那是一场更重要的比赛，我会让整个队伍付出代价。", "csp-21")
	normal("csp-21", WYJ, "你们现在还不是机器。能在考场上承认自己走错了路，然后转身回来，比假装永远正确更重要。", "csp-22")
	option("csp-22", "你会怎么回答李佳迪？", listOf(
		"只要你们还愿意来，我就会。" to "csp-23a",
		"我不能保证结果，但我会认真准备每一堂课。" to "csp-23b"
	))
	normal("csp-23a", WYJ, "只要你们还愿意来，我就会。", "csp-24")
	normal("csp-23b", WYJ, "我不能保证结果，但我会认真准备每一堂课。能保证的事情，我只说这一件。", "csp-24")
	normal("csp-24", NARRATION, "窗外的雨停了。没有烟花，没有颁奖台，只有四个初一学生围在一张成绩单旁边，第一次知道通过也不是终点。", "csp-25")
	normal("csp-25", WYJ, "从今天起，CSP-S 只是你们见过的第一扇门。下一扇门会更重，也更冷。", "csp-26")
	normal("csp-26", LZN, "那我们就一起把它推开！", "csp-27")
	normal("csp-27", NARRATION, "你没有告诉她们，自己握着手机的手也在发抖。你比任何人都清楚，所谓天才和努力，在更高的赛场上都会变成一张张冷冰冰的排名表。", null)
}

val NoipScene = PlotTree.plotTree {
	entry("noip-1")
	normal("noip-1", NARRATION, "NOIP 结束后的教室空得很快。家长们在门外低声讨论分数，走廊尽头传来打印机吐出成绩单的声音。", "noip-2")
	normal("noip-2", LZN, "老师，我是不是又考砸了？我最后那题明明会，手就是一直抖。", "noip-3")
	normal("noip-3", WYJ, "先坐下。现在不复盘最后一题，也不看别人考了多少。", "noip-4")
	normal("noip-4", LZN, "可是如果我没过呢？如果只有我没过呢？", "noip-5")
	normal("noip-5", WYM, "不会只有你。要是只有你，我就陪你一起……嗯，陪你重新学。", "noip-6")
	normal("noip-6", LZN, "吴一鸣，你这句话听起来一点都不像安慰。", "noip-7")
	normal("noip-7", WYM, "我已经很努力了。", "noip-8")
	normal("noip-8", NARRATION, "吴一鸣低头看着桌面，声音轻得像要睡着。可你听出了里面的认真。", "noip-9")
	normal("noip-9", ZHC, "结果还没有出来。我们现在能做的只有等待。", "noip-10")
	normal("noip-10", LJD, "等待也是比赛的一部分。只是这一部分没有算法。", "noip-11")
	option("noip-11", "面对无法控制的结果，你会怎么告诉她们？", listOf(
		"先把今天过完，明天再面对下一步。" to "noip-11a",
		"结果会改变计划，但不会决定你们是谁。" to "noip-11b"
	))
	normal("noip-11a", WYJ, "有。它叫接受自己无法控制的事情。先把今天过完，明天再面对下一步。", "noip-12")
	normal("noip-11b", WYJ, "有。结果会改变计划，但不会决定你们是谁。", "noip-12")
	normal("noip-12", NARRATION, "你曾经以为，教竞赛就是把知识讲清楚，把题目做出来，把一条通往胜利的路铺在学生脚下。直到今天，你才看见那条路旁边还有无数不能由你决定的东西。", "noip-13")
	normal("noip-13", LZN, "老师，你以前参加比赛的时候，也会害怕吗？", "noip-14")
	normal("noip-14", WYJ, "会。拿到 NOI Ag 的那一年，我也觉得自己下一场就会被所有人超过。拿到 ICPC Final Au 之后，这种感觉也没有消失。", "noip-15")
	normal("noip-15", LZN, "那你为什么还要一直比？", "noip-16")
	normal("noip-16", WYJ, "因为我喜欢在不知道答案的时候，继续寻找答案。可我后来才明白，比赛不是只奖励喜欢。它还会奖励时间、状态、题目顺序，甚至奖励你当天没有生病。", "noip-17")
	normal("noip-17", ZHC, "所以结果不完全代表能力。", "noip-18")
	normal("noip-18", WYJ, "不完全代表。但它会真实地改变下一张名单。残酷的地方就在这里。", "noip-19")
	normal("noip-19", LJD, "如果我考得不好，我会继续。", "noip-20")
	normal("noip-20", WYM, "我也会继续。年糕还没有学会写程序。", "noip-21")
	normal("noip-21", LZN, "那我更不能停。我还没有超过李佳迪，也没有把‘发挥失常’这个借口从字典里删掉。", "noip-22")
	normal("noip-22", ZHC, "我会把今天的每一个错误记下来。不是为了惩罚自己。是为了下一次遇到它时，能够认出来。", "noip-23")
	normal("noip-23", NARRATION, "打印机终于停止。四个人都没有立刻去拿成绩单。那一张薄薄的纸，像一扇不知道通向哪里、也不知道会把谁留下的门。", "noip-24")
	normal("noip-24", WYJ, "不管名单上写着什么，今天的课到这里。回家吃饭，睡觉。明天再面对下一步。", "noip-25")
	normal("noip-25", NARRATION, "你走出教室时，听见身后传来刘子诺压低的声音：老师是不是也很害怕？没有人回答她。", null)
}

val TeamScene = PlotTree.plotTree {
	entry("team-1")
	normal("team-1", NARRATION, "省队名单公布在一个没有特殊天气的下午。阳光照进教室，照亮了白板上还没擦干净的复杂度分析。", "team-2")
	normal("team-2", ZHC, "四个名字都在。", "team-3")
	normal("team-3", LZN, "都在！我们真的都在！这次不是模拟赛，不是校内排名，是省队！", "team-4")
	normal("team-4", WYM, "那以后是不是要更忙了？", "team-5")
	normal("team-5", LJD, "当然。省队不是奖励，是新的筛选。", "team-6")
	normal("team-6", LZN, "李佳迪，你能不能至少今天不要说这么吓人的话？", "team-7")
	normal("team-7", LJD, "我只是说事实。", "team-8")
	normal("team-8", WYJ, "她说得没错，但事实不应该抢走今天的快乐。", "team-9")
	normal("team-9", NARRATION, "你从抽屉里拿出四瓶汽水。它们很普通，甚至不是同一个牌子，是你下楼时随手买的。", "team-10")
	normal("team-10", LZN, "老师，你是不是早就知道我们能进？", "team-11")
	normal("team-11", WYJ, "我知道你们有机会。但机会不是承诺。", "team-12")
	normal("team-12", ZHC, "你一直把最坏的结果告诉我们。", "team-13")
	normal("team-13", WYJ, "因为我不希望你们把失败理解成世界突然背叛了自己。", "team-14")
	normal("team-14", WYM, "可是如果真的很努力，还是输了呢？", "team-15")
	normal("team-15", WYJ, "那就说明这一次还不够。不是说你们不值得，也不是说你们没有天赋，只是赛场只记录那一天交上去的答案。", "team-16")
	normal("team-16", LZN, "听起来好难过。", "team-17")
	normal("team-17", WYJ, "是。所以你们必须在喜欢它的时候，也学会承受它。", "team-18")
	normal("team-18", LJD, "王老师，你呢？如果我们以后都走得比你远，你会难过吗？", "team-19")
	normal("team-19", WYJ, "我会高兴。也会有一点寂寞。老师能做的，最终就是看着学生走到自己到不了的地方。", "team-20")
	normal("team-20", NARRATION, "这句话说出口后，教室安静了很久。窗外有人骑车经过，车铃声短促地响了一下。", "team-21")
	normal("team-21", ZHC, "那我们会记得你。", "team-22")
	normal("team-22", WYM, "我也会带年糕去看你。", "team-23")
	normal("team-23", LZN, "我会在采访里说，王怡钧老师最会把人骂醒。", "team-24")
	normal("team-24", LJD, "我会说，你的讲义还有改进空间。", "team-25")
	normal("team-25", WYJ, "那就约好了。你们先走到更远的地方，再回来告诉我那里是什么样。", "team-26")
	normal("team-26", NARRATION, "四瓶汽水被同时打开。气泡涌出来，像一场小得不能再小的庆祝。可你知道，真正漫长的路，才刚刚开始。", null)
}

val NoiScene = PlotTree.plotTree {
	entry("noi-1")
	normal("noi-1", NARRATION, "NOI 赛场外，你们隔着人群看见彼此。那一刻没有教室，没有白板，也没有每周日固定的三小时。", "noi-2")
	normal("noi-2", LZN, "我突然想起来，我们第一次见老师的时候，我还以为你只是来教几道题的。", "noi-3")
	normal("noi-3", WYM, "我当时只想回家看年糕。", "noi-4")
	normal("noi-4", ZHC, "我当时不知道该说什么。现在也不知道。", "noi-5")
	normal("noi-5", LJD, "我当时以为这里不会有什么值得留下的东西。", "noi-6")
	normal("noi-6", WYJ, "那现在呢？", "noi-7")
	normal("noi-7", LJD, "现在我知道，答案之外，还有一起等待答案的人。", "noi-8")
	normal("noi-8", NARRATION, "四个人都已经长高了。她们的脸上仍然保留着最初的轮廓，却不再是你第一次推门时看见的四个孩子。", "noi-9")
	normal("noi-9", WYM, "老师，比赛结束后，我们还会每周日见吗？", "noi-10")
	normal("noi-10", WYJ, "如果你们愿意。", "noi-11")
	normal("noi-11", LZN, "当然愿意！就算以后不做题，也要见面。", "noi-12")
	normal("noi-12", ZHC, "先比赛吧。", "noi-13")
	normal("noi-13", LJD, "对。真正的结果还没有写下来。", "noi-14")
	normal("noi-14", NARRATION, "发令的钟声响起。你们各自走向考场，没有人回头，因为所有人都知道，这一次不是离开，而是把共同走过的路带进自己的答案里。", "noi-15")
	normal("noi-15", WYJ, "去吧。把会做的做完，把不会的想清楚。别让一张排名表替你们决定自己是谁。", "noi-16")
	normal("noi-16", NARRATION, "多年以后，你也许会忘记某一道题的具体转移方程，却不会忘记这间合肥教室里，四个女孩如何从害怕失败，走到愿意再次提交。", "noi-17")
	normal("noi-17", NARRATION, "比赛结束后的晚宴没有想象中盛大。没有聚光灯，也没有人专门为你们准备一张写着‘四个人都成为 NOI Au’的横幅。你们只是坐在一张不大的桌子旁，面前摆着温热的饭菜，窗外是陌生城市的夜景。", "noi-18")
	normal("noi-18", LZN, "我先声明，今天谁也不许聊排名。", "noi-19")
	normal("noi-19", LJD, "你已经问过三次我的分数了。", "noi-20")
	normal("noi-20", LZN, "那是因为我关心你，不是因为我关心排名。", "noi-21")
	normal("noi-21", ZHC, "这两句话的区别需要解释。", "noi-22")
	normal("noi-22", LZN, "朱皓辰，你现在越来越像老师了。", "noi-23")
	normal("noi-23", WYM, "老师不像朱皓辰。老师会允许我们点甜品。", "noi-24")
	normal("noi-24", WYJ, "可以点。今天不看预算。", "noi-25")
	normal("noi-25", NARRATION, "刘子诺欢呼了一声。吴一鸣翻菜单时已经开始犯困，朱皓辰替她把想吃的几样圈出来，李佳迪则把四个人的奖牌整齐地放在桌边。", "noi-26")
	normal("noi-26", LJD, "王老师，你还记得最开始的目标吗？", "noi-27")
	normal("noi-27", WYJ, "记得。让你们四个人都成为 NOI Au。", "noi-28")
	normal("noi-28", LZN, "完成了。虽然过程一点也不像计划。", "noi-29")
	normal("noi-29", WYJ, "计划本来就是用来被现实修改的。", "noi-30")
	normal("noi-30", WYM, "那我们现在是不是很厉害？", "noi-31")
	normal("noi-31", WYJ, "很厉害。", "noi-32")
	normal("noi-32", WYM, "比年糕厉害吗？", "noi-33")
	normal("noi-33", WYJ, "这个要看年糕有没有参加过比赛。", "noi-34")
	normal("noi-34", WYM, "它参加过抢猫粮比赛，每次都是第一。", "noi-35")
	normal("noi-35", LZN, "那我们只能争第二了。", "noi-35a")
	normal("noi-35a", NARRATION, "甜品端上来的时候，刘子诺却忽然安静了。她把勺子搁在盘边，看着窗外陌生城市的灯，像在确认这一切是不是真的。", "noi-35b")
	normal("noi-35b", LZN, "老师，我刚才想起初一那年，我第一次考砸以后，躲在教室后面哭。那时候我以为，我这辈子都学不会在紧张的时候相信自己。", "noi-35c")
	normal("noi-35c", WYJ, "现在呢？", "noi-35d")
	normal("noi-35d", LZN, "现在我还是会紧张。只是今天我知道，紧张不等于会输。这句话，我用了整整五年才敢说出来。", "noi-35e")
	normal("noi-35e", NARRATION, "朱皓辰没有说话，只是把最后一块蛋糕分成了四份，很平均，像她做过的每一道证明题。", "noi-35f")
	normal("noi-35f", ZHC, "我一直以为稳定是把害怕藏起来。后来才明白，稳定是害怕的时候，手还没有停。", "noi-35g")
	normal("noi-35g", WYM, "我今天没有睡着。", "noi-35h")
	normal("noi-35h", LZN, "这也值得报告吗？", "noi-35i")
	normal("noi-35i", WYM, "值得。我以前总在最重要的时候困。今天我一直醒着，一直看着你们。我怕一睡着，这些人就散了。", "noi-35j")
	normal("noi-35j", NARRATION, "李佳迪把四枚奖牌又摆正了一次。她的动作很轻，却让整张桌子都安静下来。", "noi-35k")
	normal("noi-35k", LJD, "初一的时候，我问过老师：继续参加竞赛值不值得。那时候我以为我只是擅长赢，并不真的喜欢编程。", "noi-35l")
	normal("noi-35l", WYJ, "那你现在有答案了吗？", "noi-35m")
	normal("noi-35m", LJD, "有。我喜欢的从来不是排名。是解开一道题时那一瞬间的安静，还有身边有人和我一起安静。", "noi-35n")
	normal("noi-35n", NARRATION, "你看着她们，忽然发现，这四句话，恰好是五年前她们各自最害怕说出口的东西。", "noi-36")
	normal("noi-36", NARRATION, "你们笑了很久。那一晚没有人哭，没有人打开计分板，也没有人追问下一场比赛什么时候开始。你第一次看见她们只是一起吃饭、一起说废话，而不是一起等待一个结果。", "noi-37")
	normal("noi-37", NARRATION, "后来你们回了合肥。那间最初的教室已经换了新的桌椅，白板上不再有你写下的训练计划。四个人站在门口，像四位已经走了很远、却仍然记得回家路线的人。", "noi-38")
	normal("noi-38", LZN, "这里变小了。", "noi-39")
	normal("noi-39", ZHC, "是我们长大了。", "noi-40")
	normal("noi-40", WYM, "老师，年糕也老了一点。", "noi-41")
	normal("noi-41", LJD, "你为什么每次都先说年糕？", "noi-42")
	normal("noi-42", WYM, "因为它一直在等我回家。", "noi-43")
	normal("noi-43", NARRATION, "你们一起走进教室。刘子诺在原来的位置坐下，朱皓辰翻开那本已经写满的错题本，李佳迪站到白板前，吴一鸣趴在桌上，把年糕的照片摆在键盘旁边。", "noi-43a")
	normal("noi-43a", NARRATION, "刘子诺伸手摸了摸桌角。那里有一道很浅的划痕，是初一那年她因为一次失误，用笔尖反复戳出来的。", "noi-43b")
	normal("noi-43b", LZN, "这道划痕还在。我以前每次紧张就戳它，好像疼一下就能让自己清醒。", "noi-43c")
	normal("noi-43c", LZN, "现在我不需要它了。可我还是很高兴它还在，像一个证明——证明那个害怕的我，真的走到了这里。", "noi-43d")
	normal("noi-43d", NARRATION, "朱皓辰翻到错题本的第一页。那上面是她初一时写下的一句话：错误不是失败的证据，是下一次训练的入口。", "noi-43e")
	normal("noi-43e", ZHC, "这句话我一直没有改。因为它到今天还是对的。", "noi-43f")
	normal("noi-43f", NARRATION, "李佳迪拿起白板笔，却没有写题。她只在角落写下四个人的名字，然后退后一步，看了很久。", "noi-43g")
	normal("noi-43g", LJD, "初一的时候，我把自己藏在‘最强’两个字后面。现在我知道，一个人最强，是很孤独的一件事。", "noi-43h")
	normal("noi-43h", NARRATION, "吴一鸣把年糕的照片摆正。照片里的猫已经有些老了，眼神却依旧懒散而安心。", "noi-43i")
	normal("noi-43i", WYM, "年糕不会写程序，可它教会了我一件事：有人愿意等你回家，你就不算真的输。", "noi-44")
	normal("noi-44", LZN, "老师，再讲一道题吧。就一道。", "noi-45")
	normal("noi-45", WYJ, "你们都已经比我强了，还要听我讲？", "noi-46")
	normal("noi-46", LJD, "强不强和想不想听是两件事。", "noi-47")
	normal("noi-47", ZHC, "而且你讲义里还有几处可以改进。", "noi-47a")
	normal("noi-47a", WYJ, "我就知道。这句话我从初一听到现在，一个字都没变。", "noi-47b")
	normal("noi-47b", LZN, "有些话不用变。变的是说这句话的人，已经真的有资格说了。", "noi-48")
	normal("noi-48", WYJ, "我就知道。", "noi-49")
	normal("noi-49", WYM, "老师，我们以后还会每周日见吗？", "noi-50")
	normal("noi-50", WYJ, "会的。只要你们还愿意来。", "noi-50-0")
	normal("noi-50-0", NARRATION, "话音落下的一瞬，四个人几乎同时开口——", "noi-50-1")
	normal("noi-50-1", LZN, "我愿意！", "noi-50-2")
	normal("noi-50-2", WYM, "我愿意。", "noi-50-3")
	normal("noi-50-3", ZHC, "我愿意。", "noi-50-4")
	normal("noi-50-4", LJD, "我愿意。", "noi-50-5")
	normal("noi-50-5", NARRATION, "四个声音叠在一起，先是愣了一下，随即一起笑了出来。那一句‘我愿意’撞在空教室的墙上，像五年前第一堂课时，四个人齐刷刷抬头的那个瞬间。", "noi-50a")
	normal("noi-50a", NARRATION, "这句话你在初一说过，在 NOI 赛场外说过，现在又说了一遍。四个人都笑了，因为她们发现，这是你唯一一句从来没有改口的承诺。", "noi-51")
	normal("noi-51", NARRATION, "那天你们没有真的讲题。你们聊了学校、未来、要去哪里读书，也聊了以后也许不会再参加竞赛。夕阳从窗户斜进来，把四个人的影子拉得很长。", "noi-52")
	normal("noi-52", NARRATION, "你看着她们，忽然想起最开始的那个自己。那个为了挣一点生活费而接下编程班的大学生，带着 NOI Ag 和 ICPC Final Au 的光环，以为自己只要足够懂算法，就能教会别人如何赢。", "noi-53")
	normal("noi-53", WYJ, "我后来才知道，奖牌不会替你保留任何东西。它不能替你留住一个学生，不能让四个人永远坐在同一张桌子旁，也不能让某一场比赛重新开始。", "noi-54")
	normal("noi-54", WYJ, "我曾经那么在意‘OIer’这个称呼，好像只有不断做题、不断获奖、不断证明自己还配站在计分板前，才有资格把它说出口。", "noi-55")
	normal("noi-55", WYJ, "我也曾经把热爱理解成忍耐。忍耐熬夜，忍耐失败，忍耐看着别人超过自己，忍耐在已经不快乐的时候继续打开题面。只要还在训练，我就告诉自己这叫热爱；只要还不肯放弃，我就以为自己仍然是那个最初喜欢信息学竞赛的人。", "noi-56")
	normal("noi-56", WYJ, "可当一切真的完成以后，当你们都有了奖牌，都站到了我曾经想象的地方，我却突然想不起自己为什么要出发。", "noi-57")
	normal("noi-57", WYJ, "是因为喜欢那些没有答案的问题吗？是因为喜欢把一团混乱拆成清晰的状态转移吗？是因为喜欢在深夜里终于看见程序通过时，那一瞬间安静而确实的快乐吗？", "noi-58")
	normal("noi-58", WYJ, "还是因为我害怕停下来。害怕一旦不再比赛，就只剩下一个曾经拿过 NOI Ag、拿过 ICPC Final Au 的人；害怕一旦不再被叫作强者，就没有人知道我是谁；害怕所谓天赋和成就只是借来的灯，灯灭以后，我连自己都认不出来。", "noi-59")
	normal("noi-59", WYJ, "我曾经用你们的成功证明我的教学没有失败，用你们还愿意回来证明这段关系没有结束。可这是不是也意味着，我把你们的路偷偷变成了我的答案？", "noi-59a")
	normal("noi-59a", WYJ, "我记得刘子诺第一次因为‘发挥失常’躲起来哭，记得吴一鸣在最难的题面前睡着，记得朱皓辰把害怕排到最后处理，记得李佳迪问我，继续下去值不值得。", "noi-59b")
	normal("noi-59b", WYJ, "那时候我以为，我要做的是把她们各自的短板补齐，把每一块石头替她们搬走。可真正让她们走到今天的，从来不是我搬走的石头，是她们自己学会了在石头旁边绕过去、或者干脆停下来喘口气。", "noi-59c")
	normal("noi-59c", WYJ, "她们已经不需要我了。这本该是一个老师最想听见的话，可当它真的成真，我才发现自己一直偷偷害怕这一天。", "noi-60")
	normal("noi-60", WYJ, "现在你们功成名就，四个人都成为了 NOI Au。你们笑着说还会每周日回来，桌上还有没有吃完的甜品，年糕的照片还放在吴一鸣的键盘旁边。所有事情看起来都这么温柔，像一个终于被好好收束的故事。", "noi-61")
	normal("noi-61", WYJ, "可是我站在这间教室里，站在所有结果都已经兑现之后，突然不知道该把什么称作胜利。", "noi-61a")
	normal("noi-61a", NARRATION, "夕阳从窗户斜进来，落在白板角落李佳迪写下的四个名字上，也落在你自己有些花白的鬓角。教室很安静，安静得能听见楼道尽头那盏旧灯管细微的嗡鸣——和五年前的第一节课一模一样。", "noi-61b")
	normal("noi-61b", WYJ, "我把她们从害怕失败，带到了愿意再次提交。可我自己呢？我这么多年，是不是还停在那个不敢承认‘这道题我不会’的少年身上，只是把它藏进了‘老师’这个称呼里。", "noi-61c")
	normal("noi-61c", NARRATION, "你看着四个人渐渐走远的背影，又低头看了看自己的手。那双手曾经在赛场上发抖，如今握着一支快要写完的白板笔。", "noi-62")
	normal("noi-62", WYJ, "我曾经用她们的奖牌来回答这个问题。现在奖牌已经挂在了别人身上，我才发现，这道题我从来没有替自己解过。", null)
}

val GradeOneEndingScene = PlotTree.plotTree {
	entry("year-1")
	normal("year-1", NARRATION, "初一结束的那天，教室里只剩下你们五个人。校服、书包和盛夏的蝉声，把这间教室和一年前重叠在一起。", "year-2")
	normal("year-2", WYJ, "今天不做题。把电脑都合上，我们聊聊这一年。", "year-3")
	normal("year-3", LZN, "不做题？老师，你是不是终于发现我们需要休息了？", "year-4")
	normal("year-4", WYJ, "我只是发现，如果只会做题，就不知道自己为什么还要继续做题。", "year-5")
	normal("year-5", WYM, "因为题做完以后会有一种……脑袋变轻的感觉。", "year-6")
	normal("year-6", ZHC, "也可能是你睡着了。", "year-7")
	normal("year-7", WYM, "睡着以后脑袋也很轻。", "year-8")
	normal("year-8", NARRATION, "刘子诺笑了起来，笑声撞在空教室的墙上，又很快落下去。你看着四个人，忽然不知道该从谁开始。", "year-9")
	normal("year-9", WYJ, "刘子诺，你先说。你这一年最想忘掉的是什么？", "year-10")
	normal("year-10", LZN, "排名。每次排名。还有我明明会做，却因为急着提交把答案写错的时候。", "year-11")
	normal("year-11", LZN, "我有时候觉得自己很厉害，有时候又觉得自己只是运气好。最难受的是，我不知道哪个才是真的我。", "year-12")
	normal("year-12", WYJ, "两个都是真的。发挥好的你和发挥失常的你，都是你。我们要做的不是挑一个留下，而是让那个会失误的你，学会回来。", "year-13")
	normal("year-13", LZN, "那如果我一直学不会呢？", "year-14")
	normal("year-14", WYJ, "就一直练习回来。竞赛没有保证，但允许重来。", "year-15")
	normal("year-15", WYJ, "吴一鸣呢？", "year-16")
	normal("year-16", WYM, "我最想忘掉……每次大家都做到第三题，我还在看第一题。", "year-17")
	normal("year-17", WYM, "我知道自己也在进步，可是进步很慢。别人一周学会的东西，我可能要三周。老师，你会不会觉得我拖累大家？", "year-18")
	normal("year-18", LZN, "不会！你只是启动得慢，但是你有时候会突然想到特别奇怪、特别厉害的东西。", "year-19")
	normal("year-19", WYM, "奇怪也算厉害吗？", "year-20")
	normal("year-20", ZHC, "能解决问题就算。", "year-21")
	normal("year-21", WYJ, "吴一鸣，你不是一张成绩单。你困的时候需要休息，醒着的时候也确实在努力。", "year-22")
	normal("year-22", WYM, "可是年糕很可爱。", "year-23")
	normal("year-23", WYJ, "你也可以先从可爱开始。", "year-24")
	normal("year-24", NARRATION, "她低头笑了一下，白色长发从肩头滑下来。那是她第一次没有立刻用困倦把话题盖过去。", "year-25")
	normal("year-25", WYJ, "朱皓辰，你呢？", "year-26")
	normal("year-26", ZHC, "我没有特别想忘掉的事。但是我发现，稳定不等于没有害怕。", "year-27")
	normal("year-27", ZHC, "我只是习惯把害怕放到最后处理。现在我想先处理它。", "year-28")
	normal("year-28", WYJ, "这是很重要的进步。", "year-29")
	normal("year-29", WYJ, "李佳迪，你一直没有说话。", "year-30")
	normal("year-30", LJD, "我在想，继续参加竞赛是否值得。", "year-31")
	normal("year-31", LZN, "你怎么会问这个？你不是最喜欢难题吗？", "year-32")
	normal("year-32", LJD, "喜欢难题，不代表喜欢被排名。每次成绩出来，所有人只问我为什么不是第一。没有人问那道题本身。", "year-33")
	normal("year-33", LJD, "有时候我怀疑，我只是擅长赢，而不是喜欢编程。", "year-34")
	normal("year-34", NARRATION, "这一次没有人马上回答。连刘子诺都安静下来。窗外的蝉声很大，像有人不停地提醒夏天已经到了。", "year-35")
	normal("year-35", WYJ, "我不能替你回答值不值得。但如果你留下，我希望你是因为还愿意对没有答案的问题感到好奇。", "year-36")
	normal("year-36", LJD, "如果有一天我不再好奇了呢？", "year-37")
	normal("year-37", WYJ, "那就停下来。目标是我的，不是你们必须背负的债。", "year-38")
	normal("year-38", WYJ, "我能做的是把路照亮一点。走不走、走多远，最后还是你们自己的事。", "year-39")
	normal("year-39", NARRATION, "你第一次承认自己并不确定，而四个人第一次听见，老师也可能害怕失败。", "year-40")
	normal("year-40", LZN, "那我想继续。我还想知道自己能不能在紧张的时候做完一道题。", "year-41")
	normal("year-41", WYM, "我也继续。暑假可以少一点题，多一点午睡吗？", "year-42")
	normal("year-42", ZHC, "我继续。下一年我想学会更快地处理害怕。", "year-43")
	normal("year-43", LJD, "我继续。不是为了证明自己是第一。至少现在不是。", "year-choice")
	option("year-choice", "初一结束，你想留给她们哪一句话？", listOf(
		"这一年你们都长大了，暑假请好好休息。" to "year-choice-a",
		"别急着变强，先记住今天为什么想继续。" to "year-choice-b"
	))
	normal("year-choice-a", WYJ, "这一年你们都长大了。暑假请好好休息，把自己养回来，再来谈下一场比赛。", "year-44")
	normal("year-choice-b", WYJ, "别急着变强。先记住今天你们各自写下的理由，那比任何一道题都更容易在半路弄丢。", "year-44")
	normal("year-44", WYJ, "好。那初二见。", "year-45")
	normal("year-45", NARRATION, "你收起白板上的最后一行字。那不是算法，也不是训练计划，而是四个人各自写下的理由。夏天很长，接下来的比赛会更残酷，可至少这一刻，她们不是被任何一张名单推着向前。", null)
}

val FailureScene = failureScene("CSP-S")

/**
 * 失败结局。不同阶段（CSP-S / NOIP / 省队 / NOI）有各自的开场，
 * 之后汇入同一段王怡钧的第一人称长篇独白（failure-52 起）。
 */
fun failureScene(checkpoint: String): PlotTree = PlotTree.plotTree {
	entry("failure-1")
	failureOpening(checkpoint)
	failureReflection()
}

/** 各阶段失败的开场：从名单/结果公布，到四个人各自的反应，最终交回王怡钧，衔接到 failure-52。 */
private fun PlotTree.Builder.failureOpening(checkpoint: String) {
	when (checkpoint) {
		"NOIP" -> {
			normal("failure-1", NARRATION, "NOIP 的成绩比 CSP-S 晚了整整两周。你们一起熬过了那两周，却没能一起熬过这一页。", "failure-2")
			normal("failure-2", LZN, "老师……我们不是都过了 CSP-S 吗？为什么到这里就……", "failure-3")
			normal("failure-3", WYJ, "因为每一扇门都比上一扇更窄。这一次，我们没能全部挤进去。", "failure-4")
			normal("failure-4", NARRATION, "名单上少了一个熟悉的名字。空出来的那一行，正好是你们四个曾经并排坐着的位置之一。", "failure-5")
		}
		"省队" -> {
			normal("failure-1", NARRATION, "省队名单公布在一个很普通的傍晚。你们本以为，走到这一步的人不会再被刷下来。", "failure-2")
			normal("failure-2", LZN, "省队……老师，省队只有这么几个名额，对不对？", "failure-3")
			normal("failure-3", WYJ, "对。到了这里，光是‘很好’已经不够了。", "failure-4")
			normal("failure-4", NARRATION, "四个名字里，有人被留在了名单外面。越往上走，一个失误的代价就越沉。这一次，代价落在了你们中间。", "failure-5")
		}
		"NOI" -> {
			normal("failure-1", NARRATION, "这是最后一扇门。走到 NOI 选拔的人，早已不是当年那四个连树都会说错的初一学生。", "failure-2")
			normal("failure-2", LZN, "都到这一步了……老师，我们只差最后一点点。", "failure-3")
			normal("failure-3", WYJ, "我知道。可竞赛不会因为你走得够远，就在最后一步对你手下留情。", "failure-4")
			normal("failure-4", NARRATION, "名单停在了 NOI 的门槛前。你们走过了 CSP-S、NOIP、省队，却在最靠近山顶的地方，被风留了下来。", "failure-5")
		}
		else -> {
			normal("failure-1", NARRATION, "名单公布的页面加载了很久。那几秒钟里，教室里的钟声被放大得近乎刺耳。", "failure-2")
			normal("failure-2", LZN, "老师……你看到了吗？", "failure-3")
			normal("failure-3", WYJ, "看到了。", "failure-4")
			normal("failure-4", NARRATION, "四个名字没有排在一起。中间隔着一行空白，像一条谁也没有说出口的河。", "failure-5")
		}
	}
	normal("failure-5", WYM, "是不是刷新错了？再刷一次吧。", "failure-6")
	normal("failure-6", ZHC, "我已经刷新过了。", "failure-7")
	normal("failure-7", WYM, "那就再刷新一次。", "failure-8")
	normal("failure-8", LJD, "不用了。结果不会因为我们不看它就消失。", "failure-9")
	normal("failure-9", LZN, "你能不能别说了？", "failure-10")
	normal("failure-10", LJD, "我只是说事实。", "failure-11")
	normal("failure-11", LZN, "我知道是事实！我就是知道，才不知道该怎么办！", "failure-12")
	normal("failure-12", NARRATION, "刘子诺的声音撞在墙上。她立刻咬住嘴唇，仿佛只要安静得足够快，刚才那句话就没有说过。", "failure-13")
	normal("failure-13", WYJ, "今天先回家。", "failure-14")
	normal("failure-14", LZN, "我不想回家。", "failure-15")
	normal("failure-15", WYJ, "为什么？", "failure-16")
	normal("failure-16", LZN, "因为他们会问。问我为什么别人可以，我不可以。问我是不是没有认真，问我是不是又发挥失常。可是我已经很认真了。", "failure-17")
	normal("failure-17", LZN, "我每天都在想那几道题。我吃饭的时候想，睡觉的时候想，看到别人提交的时候也想。我只是……在那一天没有做出来。", "failure-18")
	normal("failure-18", WYJ, "我知道。", "failure-19")
	normal("failure-19", LZN, "你不知道。你每次都知道下一步该做什么。你不会像我一样，明明走了这么久，最后发现自己根本没有走到那里。", "failure-20")
	normal("failure-20", NARRATION, "你想反驳，却发现自己手里没有一句足够诚实的话。你可以说她进步了，可以说一次比赛不能定义她，可名单上那个空缺仍然在那里。", "failure-21")
	normal("failure-21", WYJ, "对不起。", "failure-22")
	normal("failure-22", LZN, "你为什么道歉？", "failure-23")
	normal("failure-23", WYJ, "因为我以为只要计划足够好、题目讲得足够清楚，就能把你们都带到下一站。我把一件没有保证的事，说得像一定会发生。", "failure-24")
	normal("failure-24", ZHC, "老师，你没有骗我们。", "failure-25")
	normal("failure-25", WYJ, "可我还是让你们相信了，努力会自动兑换成结果。", "failure-26")
	normal("failure-26", WYM, "那努力是不是没有用？", "failure-27")
	normal("failure-27", WYJ, "不是。只是它没有你们希望的那么公平。", "failure-28")
	normal("failure-28", WYM, "不公平的话，为什么还要做？", "failure-29")
	normal("failure-29", WYJ, "我不知道。也许因为题目被解出来的那一刻是真的，也许因为有人愿意在失败以后再来一次。", "failure-30")
	normal("failure-30", LJD, "如果我留下，她不留下呢？", "failure-31")
	normal("failure-31", NARRATION, "李佳迪看着那个空缺，第一次没有把话说得像结论。她的手指按在桌面上，按得发白。", "failure-32")
	normal("failure-32", ZHC, "她不是不想留下。她只是需要先回到自己的生活里。", "failure-33")
	normal("failure-33", LZN, "那我们呢？我们还能像以前一样四个人一起上课吗？", "failure-34")
	normal("failure-34", WYJ, "我不知道。", "failure-35")
	normal("failure-35", NARRATION, "这是你第一次在她们面前说不知道。也正因为如此，所有人都明白，这不是一句安慰。", "failure-36")
	normal("failure-36", WYM, "那我可以再来一次吗？不是比赛。我想把今天没写完的题写完。", "failure-37")
	normal("failure-37", WYJ, "可以。", "failure-38")
	normal("failure-38", LZN, "我也想来。虽然我现在很讨厌这张成绩单，但我还没有讨厌到想把这一年全部丢掉。", "failure-39")
	normal("failure-39", ZHC, "我会把缺少的部分补上。即使以后不再一起参加同一场比赛，也应该知道自己到底差在哪里。", "failure-40")
	normal("failure-40", LJD, "我会等她。", "failure-41")
	normal("failure-41", WYJ, "李佳迪，你不必替任何人等。", "failure-42")
	normal("failure-42", LJD, "我知道。但这是我的选择。", "failure-43")
	normal("failure-43", NARRATION, "放学铃响了。没有人立刻起身。桌面上的成绩单被四个人围在中间，像一场已经结束、却没有人愿意先宣布结束的比赛。", "failure-44")
	normal("failure-44", LZN, "老师，明天还上课吗？", "failure-45")
	normal("failure-45", WYJ, "明天不上。先回家，吃饭，睡觉。", "failure-46")
	normal("failure-46", LZN, "那下周呢？", "failure-47")
	normal("failure-47", WYJ, "下周日，我会在这里。", "failure-48")
	normal("failure-48", NARRATION, "你没有说‘我们还会成功’，也没有说‘一切都会好起来’。有些话在名单出来以后，轻得像谎言。", "failure-49")
	normal("failure-49", WYJ, "来不来，由你们决定。无论来不来，你们都不是这张纸上的一个空缺。", "failure-50")
	normal("failure-50", NARRATION, "四个人陆续走出教室。刘子诺最后回头看了一眼黑板，那里还留着你们几个月前写下的目标：四个人，都成为 NOI Au。", "failure-51")
	normal("failure-51", NARRATION, "你拿起板擦，却没有立刻擦掉它。直到天色完全暗下来，你才明白，有些目标可以结束，有些人不会因此从故事里消失。", "failure-52")
}

/** 失败结局共用的第一人称长篇独白（王怡钧回望自己的 OI 经历），四个阶段完全一致。 */
private fun PlotTree.Builder.failureReflection() {
	normal("failure-52", WYJ, "我也曾经以为，只要足够努力，就一定能把想要的东西拿到手。", "failure-53")
	normal("failure-53", WYJ, "高二那年拿到 NOI Ag 以后，所有人都说我已经找到了正确的路。他们说我聪明，说我有天赋，说我以后一定会走得很远。那些话听起来像祝福，后来却慢慢变成了我不敢承认的东西。", "failure-54")
	normal("failure-54", WYJ, "因为只要有人说你是天才，你就很难再告诉别人：这道题我不会。你会害怕。害怕他们发现，所谓天赋只是很多个晚上没有被看见的挣扎，害怕下一次比赛证明他们都看错了。", "failure-55")
	normal("failure-55", NARRATION, "你靠在讲台边，想起那时的自己。", "failure-56")
	normal("failure-56", WYJ, "我参加过准备得很充分，却在开场后完全找不到状态的比赛。坐在屏幕前，我认识题目里的每一个名词，却连第一步应该写什么都想不起来。旁边的人在不断提交，计分板上的名字一行一行地向上走，只有我的位置像钉在原地。", "failure-57")
	normal("failure-57", WYJ, "我也有过明明会做，却因为一个下标、一个边界、一个自以为不会出错的细节，把整道题交成零分的时候。那几分钟里，我甚至不敢抬头。不是因为别人会责备我，而是因为我知道，如果是平时的我，应该不会犯这种错误。", "failure-58")
	normal("failure-58", WYJ, "可比赛里的我，不是平时的我。会生病，会疲惫，会紧张，会在最不该犹豫的时候犹豫。那些我以为已经被训练消灭的软弱，只是躲在了更深的地方，等着某一天在所有人都看着我的时候出现。", "failure-59")
	normal("failure-59", WYJ, "我曾经因为一次失败，把接下来几个月的每个晚上都变成审判。我反复打开代码，反复看那一行错误，仿佛只要把它看得足够久，过去就会允许我重新提交一次。", "failure-60")
	normal("failure-60", WYJ, "当然不会。程序不会因为你后悔就重新运行，名单不会因为你哭过就重新打印。那时候我最恨的不是输，而是第二天醒来以后，世界还在继续，只有我还被困在比赛结束的那一刻。", "failure-61")
	normal("failure-61", NARRATION, "你看着黑板上那行字。水笔的墨迹落在指尖，细得几乎看不见。", "failure-62")
	normal("failure-62", WYJ, "后来我拿到了 ICPC Final Au。别人又开始说我证明了自己，说那些失败只是通往成功的台阶。可他们不知道，台阶这个说法有多轻松。它会把摔下去时的疼痛全部藏掉，好像只要最后站得够高，之前摔过多少次都不重要。", "failure-63")
	normal("failure-63", WYJ, "我当然为那枚金牌高兴过。也确实有过觉得自己终于被世界承认的时刻。可是庆祝结束以后，新的比赛、新的对手、新的计分板又会出现。你刚刚证明自己没有那么差，下一场就必须重新证明一次。", "failure-64")
	normal("failure-64", WYJ, "OI 的残酷从来不只是它会淘汰人。更残酷的是，它会让你把一次结果误认为自己的全部，把别人偶然的一次领先看成自己永远无法抵达的高度，把身边一起训练的人看成必须跨过去的障碍。", "failure-64a")
	// —— 长篇独白中间，让玩家参与、但不改变走向的一次停顿 ——
	normal("failure-64a", NARRATION, "你说到这里停了下来，喉咙有些发紧。空教室里，你几乎是在问自己，也像是在问屏幕外那个一直陪着你走到这里的人。", "failure-64-choice")
	option("failure-64-choice", "如果此刻只能对自己说一句，你会承认什么？", listOf(
		"我也曾经把身边的人，看成必须跨过去的障碍。" to "failure-64b",
		"我至今都没能完全放下那块计分板。" to "failure-64c"
	))
	normal("failure-64b", WYJ, "我也曾经把身边的人，看成必须跨过去的障碍。说出口才发现，这句话原来这么沉。", "failure-64d")
	normal("failure-64c", WYJ, "我至今都没能完全放下那块计分板。它不在赛场上了，却还挂在我心里。", "failure-64d")
	normal("failure-64d", NARRATION, "无论你承认的是哪一件，水笔的墨迹都一样静静落着。有些话说出来不会让门重新打开，但至少，你不再假装自己没有想过。", "failure-65")
	normal("failure-65", WYJ, "我也做过这种事。我看着同学的排名，偷偷计算自己还差多少；我在别人进步的时候先感到害怕，而不是替他高兴；我把‘我想赢’说得很大声，却不敢承认自己其实更害怕输。", "failure-66")
	normal("failure-66", WYJ, "所以后来我看见你们的时候，才会那么急着把所有东西都教给你们。我想把我走过的弯路提前填平，把所有可能出错的地方提前标出来。我以为这样就能保护你们。", "failure-67")
	normal("failure-67", WYJ, "可我忘了，真正的老师不是替学生把路上的石头全部搬走。那样走到最后的人，甚至不知道自己曾经跨过什么。老师能做的，也许只是学生摔倒以后，不要因为摔倒的姿势不好看，就假装没有看见。", "failure-68")
	normal("failure-68", WYJ, "今天我没有把你们四个人都带到下一站。这个事实不会因为我说了多少漂亮话而改变。目标失败了，训练计划失败了，我作为老师的判断也失败了。", "failure-69")
	normal("failure-69", WYJ, "我很想告诉刘子诺，她其实已经赢了；想告诉吴一鸣，她比自己想象中更好；想告诉朱皓辰，稳定本身就是了不起的能力；想告诉李佳迪，不要因为别人留下就觉得自己欠了谁。可是这些话都不够。因为她们今天失去的，是真实存在的一扇门。", "failure-70")
	normal("failure-70", WYJ, "我不能用‘你已经很努力了’把那扇门变回来，也不能用‘以后还有机会’假装今天没有那么疼。努力有时候不会兑换成结果，机会有时候也不会按时回来。人只能在这些都不保证的时候，决定自己还要不要继续做一个愿意尝试的人。", "failure-71")
	normal("failure-71", NARRATION, "空教室里只剩下墙上的钟。你忽然想起自己第一次拿到 NOI Ag 的晚上，想起后来站在 ICPC 赛场上的灯光，也想起那些没有人知道的、输了以后一个人回宿舍的夜晚。", "failure-72")
	normal("failure-72", WYJ, "我并不是因为从来没有失败，才有资格站在这里。恰恰相反，是因为我知道失败不会立刻结束痛苦，才不敢轻易对你们说‘没关系’。有关系。今天当然有关系。你们会难过，会不甘，会在很长一段时间里怀疑自己。", "failure-73")
	normal("failure-73", WYJ, "但请你们记住，失败只能证明这一次没有通过。它不能证明你们不配站在赛场上，不能证明你们的努力毫无意义，也不能替你们决定以后要成为怎样的人。", "failure-74")
	normal("failure-74", WYJ, "如果你们愿意回来，我会把黑板擦干净，重新写一份计划。不是为了假装今天没有发生，而是因为今天发生过，所以我们知道下一次要从哪里开始。", "failure-75")
	normal("failure-75", WYJ, "如果你们不愿意回来，我也不会怪你们。请把电脑收好，把错题本放进书包，回家吃一顿热饭。你们的人生不能只剩下一场比赛，不能只剩下一个老师，不能只剩下这句‘四个人都成为 NOI Au’。", "failure-76")
	normal("failure-76", WYJ, "我曾经花了很久，才明白人不是因为赢了才值得被留下。现在我希望你们不用像我一样，等到失去很多东西以后，才学会相信这句话。", "failure-77")
	normal("failure-77", NARRATION, "你终于把板擦放到黑板上，却只擦掉了目标下面的日期。那行字仍然留下，水笔痕迹被擦得模糊，像一个不再要求兑现、却没有被彻底否认的愿望。", "failure-78")
	normal("failure-78", WYJ, "对不起，今天没能把你们一起送过去。谢谢你们曾经相信我，也谢谢你们让我重新想起，自己为什么还愿意坐在一间普通教室里，等下一道没有答案的题。", "failure-79")
	normal("failure-79", NARRATION, "夜色从窗户爬进来。你关掉最后一盏灯，锁上合肥这间普通教室的门。明天不会因为今天的失败而变得容易，可明天仍然会到来。", "failure-80")
	normal("failure-80", NARRATION, "而在门外很远的地方，四个女孩各自走在回家的路上。她们没有带走那张名单，却把这一年所有做过的题、哭过的夜、彼此等过的时刻，悄悄带在了身上。", null)
}

/** 各阶段的失败结局，开场不同、独白共用。 */
val NoipFailureScene = failureScene("NOIP")
val TeamFailureScene = failureScene("省队")
val NoiFailureScene = failureScene("NOI")

val AfterNoipScene = PlotTree.plotTree {
	entry("after-noip-1")
	normal("after-noip-1", NARRATION, "NOIP 成绩公布后的第三个周日，教室里多了一张打印出来的排名表。它被贴在白板旁边，四个人谁也没有先去看。", "after-noip-2")
	normal("after-noip-2", LZN, "老师，先说好，不管我排第几，你都不能把我从计划里删掉。", "after-noip-3")
	normal("after-noip-3", WYJ, "我什么时候说过要删掉你？", "after-noip-4")
	normal("after-noip-4", LZN, "你没说，但成绩单会说。成绩单最会替别人说话。", "after-noip-5")
	normal("after-noip-5", NARRATION, "刘子诺的手指在桌面上敲了几下。她仍然很吵，只是每一句玩笑后面，都藏着一次确认。", "after-noip-6")
	normal("after-noip-6", ZHC, "这次排名不能直接决定省队。", "after-noip-7")
	normal("after-noip-7", LZN, "可它会决定别人怎么看我们。", "after-noip-8")
	normal("after-noip-8", LJD, "别人怎么看我们，本来就不是训练目标。", "after-noip-9")
	normal("after-noip-9", LZN, "你当然可以这么说。你排在前面。", "after-noip-10")
	normal("after-noip-10", NARRATION, "教室安静下来。李佳迪抬起眼睛，蓝色瞳孔里没有愤怒，只有一瞬间被刺中的茫然。", "after-noip-11")
	normal("after-noip-11", LJD, "我排在前面，也不代表我不知道害怕。", "after-noip-12")
	normal("after-noip-12", LZN, "那你为什么每次都看起来一点都不怕？", "after-noip-13")
	normal("after-noip-13", LJD, "因为如果我说我怕，所有人都会更害怕。", "after-noip-14")
	normal("after-noip-14", NARRATION, "这句话让刘子诺停了下来。她第一次意识到，李佳迪的高冷也可能是一种责任，而不是天生的距离感。", "after-noip-15")
	normal("after-noip-15", WYM, "那我呢？我排得很后。", "after-noip-16")
	normal("after-noip-16", ZHC, "你没有排得很后。", "after-noip-17")
	normal("after-noip-17", WYM, "可是比你们都后。", "after-noip-18")
	normal("after-noip-18", WYJ, "排名是排序，不是距离。你和她们之间的差距，不能只用一列数字解释。", "after-noip-19")
	normal("after-noip-19", WYM, "可比赛只看数字。", "after-noip-20")
	normal("after-noip-20", WYJ, "是。所以我们要学会两件事：在比赛里认真对待数字，在比赛外不把自己缩成数字。", "after-noip-21")
	normal("after-noip-21", ZHC, "省队选拔会更残酷。可能不是四个人一起进去。", "after-noip-22")
	normal("after-noip-22", LZN, "你能不能不要把这句话说得这么平静？", "after-noip-23")
	normal("after-noip-23", ZHC, "我不平静。只是我觉得应该提前知道。", "after-noip-24")
	normal("after-noip-24", WYJ, "她说得对。接下来的训练，会出现真正的竞争。你们可能坐在同一间教室，走不同的路。", "after-noip-25")
	normal("after-noip-25", LZN, "如果只有三个人进了呢？", "after-noip-26")
	normal("after-noip-26", WYJ, "没有人有资格要求另一个人留下，也没有人应该因为自己留下而道歉。", "after-noip-27")
	normal("after-noip-27", LZN, "这听起来一点都不像我们想要的故事。", "after-noip-28")
	normal("after-noip-28", WYJ, "现实通常不是为了像故事才发生的。", "after-noip-29")
	normal("after-noip-29", LJD, "那我们还要一起训练吗？", "after-noip-30")
	normal("after-noip-30", WYJ, "如果你们愿意。", "after-noip-31")
	normal("after-noip-31", LJD, "我愿意。", "after-noip-32")
	normal("after-noip-32", ZHC, "我也愿意。", "after-noip-33")
	normal("after-noip-33", WYM, "我会慢一点，但我会来。", "after-noip-34")
	normal("after-noip-34", LZN, "那我也来。可是我先说，我还是会想赢。", "after-noip-35")
	normal("after-noip-35", WYJ, "想赢没有错。只要你最后想赢的，不是她们离开。", "after-noip-36")
	normal("after-noip-36", NARRATION, "刘子诺低头看着排名表，终于伸手把它从白板上取下来。她没有撕掉，只把它折好，放进了自己的文件夹。", "after-noip-37")
	normal("after-noip-37", LZN, "我会记住今天。不是因为我排第几，是因为我差点把朋友当成敌人。", "after-noip-38")
	normal("after-noip-38", LJD, "我们本来就是竞争对手。", "after-noip-39")
	normal("after-noip-39", LZN, "那就当竞争对手，也当朋友。两件事不能同时成立吗？", "after-noip-40")
	normal("after-noip-40", LJD, "可以。", "after-noip-41")
	normal("after-noip-41", NARRATION, "李佳迪说得很轻。可那两个字落下来时，像是她亲手把一扇一直关着的门，往旁边让出了一点位置。", "after-noip-42")
	normal("after-noip-42", WYJ, "从今天开始，训练分成两部分。一起学，一起复盘；比赛时，各自承担自己的结果。", "after-noip-43")
	normal("after-noip-43", ZHC, "如果有人被留下呢？", "after-noip-44")
	normal("after-noip-44", WYJ, "留下的人继续走，没被选中的人也继续生活。你们可以难过，但不能把对方的未来当成自己的罪证。", "after-noip-45")
	normal("after-noip-45", NARRATION, "没人回答。窗外传来晚高峰的车声，合肥的街道照常向前。白板上的排名表已经取下，只剩下四枚胶带留下的痕迹。", "after-noip-46")
	normal("after-noip-46", WYM, "老师，今天可以讲新题了吗？", "after-noip-choice")
	option("after-noip-choice", "省队竞争在即，你决定接下来怎么带她们？", listOf(
		"照常讲新题，把节奏稳住。" to "after-noip-choice-a",
		"先补最短板，谁弱补谁。" to "after-noip-choice-b"
	))
	// —— 分支 A：稳住节奏，代价是最慢的人被甩得更远 ——
	normal("after-noip-choice-a", WYJ, "照常讲新题。越是临近选拔，越不能让恐慌打乱节奏。", "after-noip-choice-a2")
	normal("after-noip-choice-a2", NARRATION, "新题一道接一道。李佳迪和朱皓辰跟得很紧，刘子诺咬着牙也追了上来。只有吴一鸣的进度条卡在半途，屏幕上那道题一直没有提交。", "after-noip-choice-a3")
	normal("after-noip-choice-a3", WYM, "……我又是最后一个。", "after-noip-choice-a4")
	normal("after-noip-choice-a4", WYJ, "你不是没跟上，是这周的节奏对你太快了。这笔账我记着，之后单独补给你。", "after-noip-choice-a5")
	normal("after-noip-choice-a5", NARRATION, "她点点头，却把年糕的照片翻了过去，扣在桌上。那一整节课，她再没有抬起头。你知道，稳住整体节奏这件事，是有人替它付了代价的。", "after-noip-47")
	// —— 分支 B：先补短板，代价是整体进度被拖慢、最强的人先急了 ——
	normal("after-noip-choice-b", WYJ, "今天先不赶进度。谁的短板最明显，我们就先补谁。", "after-noip-choice-b2")
	normal("after-noip-choice-b2", NARRATION, "你把最基础的一类题重新拆开讲。吴一鸣第一次在全班面前独立做完了一道，红色的眼睛亮了起来。", "after-noip-choice-b3")
	normal("after-noip-choice-b3", WYM, "原来我也能做出来。", "after-noip-choice-b4")
	normal("after-noip-choice-b4", LJD, "老师，这些我早就会了。我们这样，会不会比别的省队苗子慢半拍？", "after-noip-choice-b5")
	normal("after-noip-choice-b5", WYJ, "会慢半拍。但一支队伍的下限，往往比它的上限更能决定它能走多远。这半拍，我替你们担着。", "after-noip-choice-b6")
	normal("after-noip-choice-b6", NARRATION, "李佳迪没有再说话，只是把自己的进度表往后压了压。补短板换来了吴一鸣的信心，也换来了最强的那个人第一次被迫等待。得失都真实地留在了这间教室里。", "after-noip-47")
	normal("after-noip-47", WYJ, "可以。今天讲最短路。", "after-noip-48")
	normal("after-noip-48", LZN, "最短路听起来像一个很好的愿望。", "after-noip-49")
	normal("after-noip-49", WYJ, "可惜竞赛里不一定存在。", "after-noip-50")
	normal("after-noip-50", NARRATION, "你在黑板上写下第一个点。四个人重新打开电脑。没有人知道未来会把谁送进省队，但至少此刻，她们仍然坐在同一盏灯下。", null)
}

val BeforeTeamScene = PlotTree.plotTree {
	entry("team-before-1")
	normal("team-before-1", NARRATION, "省队选拔前一个月，训练群里发来一份通知：名额有限，按最终成绩录取。通知只有两行字，四个人却盯了很久。", "team-before-2")
	normal("team-before-2", LZN, "‘名额有限’是什么意思？不是说我们一起参加吗？", "team-before-3")
	normal("team-before-3", ZHC, "一起参加选拔，不等于一起被选中。", "team-before-4")
	normal("team-before-4", LZN, "我知道字面意思。我是不想听懂。", "team-before-5")
	normal("team-before-5", NARRATION, "她把手机扣在桌上，粉色短发被窗外的风吹得有些乱。平时她会立刻说很多话，可这次没有。", "team-before-6")
	normal("team-before-6", WYJ, "接下来训练会更接近正式选拔。我们不再只看谁会做题，而要看谁能在有限时间里，把自己的能力交出来。", "team-before-7")
	normal("team-before-7", WYM, "如果我交不出来呢？", "team-before-8")
	normal("team-before-8", WYJ, "那就面对结果，再决定下一步。", "team-before-9")
	normal("team-before-9", WYM, "老师，你说得好像下一步一定存在。", "team-before-10")
	normal("team-before-10", WYJ, "不一定存在同一条路。但人生不会因为一场选拔就只剩下一个方向。", "team-before-11")
	normal("team-before-11", LJD, "如果方向不同，为什么还要训练？", "team-before-12")
	normal("team-before-12", WYJ, "因为你们想知道自己能走到哪里。答案未必是名额，但问题仍然值得回答。", "team-before-13")
	normal("team-before-13", LJD, "你以前也参加过这种名额有限的选拔吗？", "team-before-14")
	normal("team-before-14", WYJ, "参加过。那时我也认为，只要我比别人多做几道题，就应该得到一个位置。后来我发现，位置不是‘应该’这个词能争来的。", "team-before-15")
	normal("team-before-15", WYJ, "它只看当天的分数。你可能比另一个人准备得更久，理解得更深，走过更远的路，但如果当天少拿了十几分，名单仍然只会写另一个名字。", "team-before-16")
	normal("team-before-16", LZN, "这太不公平了。", "team-before-17")
	normal("team-before-17", WYJ, "是。", "team-before-18")
	normal("team-before-18", LZN, "你至少应该说‘比赛是公平的’。", "team-before-19")
	normal("team-before-19", WYJ, "我不想用这种话骗你们。比赛可以有规则，但规则不等于公平。有人当天身体不舒服，有人睡不好，有人遇到最擅长的题型，也有人在最熟悉的地方犯最低级的错。", "team-before-20")
	normal("team-before-20", ZHC, "那我们还能准备什么？", "team-before-21")
	normal("team-before-21", WYJ, "准备那些即使不公平，也仍然能由你们控制的部分。读题、取舍、检查、心态，以及输了以后不把自己变成一个讨厌的人。", "team-before-22")
	normal("team-before-22", NARRATION, "第一次选拔模拟赛开始。四个人坐在教室的四个角落，屏幕上的题目完全相同，计分板却把她们分成了四条不同的命运。", "team-before-23")
	normal("team-before-23", LJD, "这题的最优解是网络流。", "team-before-24")
	normal("team-before-24", LZN, "等等，我还在读题！", "team-before-25")
	normal("team-before-25", ZHC, "先确认边界。", "team-before-26")
	normal("team-before-26", WYM, "我觉得可以从暴力开始。", "team-before-27")
	normal("team-before-27", NARRATION, "两个小时后，李佳迪提交了最难的一题，朱皓辰稳定拿分，刘子诺在两道题之间反复犹豫，吴一鸣终于写出了自己的暴力解，却因为时间不够没有完成优化。", "team-before-28")
	normal("team-before-28", LZN, "我又输了。", "team-before-29")
	normal("team-before-29", WYJ, "模拟赛不是名单。", "team-before-30")
	normal("team-before-30", LZN, "可名单就是由这些东西组成的！一次一次的分数，一次一次的‘再努力一点’，最后把人分成能留下和不能留下。", "team-before-31")
	normal("team-before-31", LZN, "我不想因为我考得差，就让你们里面少一个人。更不想因为我偶尔发挥好，就让别人觉得是我抢走了位置。", "team-before-32")
	normal("team-before-32", WYJ, "没有谁抢走谁的位置。名额本来就不是任何人的私人物品。", "team-before-33")
	normal("team-before-33", LZN, "你说得轻松。要是最后只有三个人进，留下的那个人每天都会想：如果当时另一个人发挥差一点，进去的就是我。", "team-before-34")
	normal("team-before-34", ZHC, "被选中的人也会想：如果我少做对一道题，留下的就是她。", "team-before-35")
	normal("team-before-35", NARRATION, "朱皓辰的声音仍然平静，可她把草稿纸的一角捏出了深深的褶皱。", "team-before-36")
	normal("team-before-36", LJD, "所以被选中也不是纯粹的胜利。", "team-before-37")
	normal("team-before-37", WYJ, "从来不是。很多人只看见名单上向上的名字，没有看见那些名字背后留下的人。", "team-before-38")
	normal("team-before-38", WYM, "那如果我没有被选中，你们还会来上课吗？", "team-before-39")
	normal("team-before-39", LZN, "会。", "team-before-40")
	normal("team-before-40", LJD, "会。", "team-before-41")
	normal("team-before-41", ZHC, "会。", "team-before-42")
	normal("team-before-42", WYM, "你们回答得好快。", "team-before-43")
	normal("team-before-43", LZN, "因为这根本不需要想。", "team-before-44")
	normal("team-before-44", WYJ, "可你们也要明白，进省队的人会有新的训练、新的队友和新的时间安排。你们可能不能再像现在这样每周都坐在同一间教室。", "team-before-45")
	normal("team-before-45", WYM, "所以还是会分开。", "team-before-46")
	normal("team-before-46", WYJ, "可能会。", "team-before-47")
	normal("team-before-47", NARRATION, "吴一鸣低头看着桌角，像是忽然发现这间教室也有一天会变成过去。", "team-before-48")
	normal("team-before-48", WYM, "我不喜欢‘可能’。", "team-before-49")
	normal("team-before-49", WYJ, "我也不喜欢。可是提前知道会失去，不能让我们假装现在没有拥有过。", "team-before-50")
	normal("team-before-50", LJD, "如果最后只有我进了，我不会把它当成她们的失败。", "team-before-51")
	normal("team-before-51", LZN, "你最好记住。", "team-before-52")
	normal("team-before-52", LJD, "如果最后只有你进了，我也不会把它当成我的失败。", "team-before-53")
	normal("team-before-53", LZN, "……我会努力不这么想。", "team-before-54")
	normal("team-before-54", ZHC, "如果最后谁都没有进呢？", "team-before-55")
	normal("team-before-55", WYJ, "那我们就一起把今天的错题整理完。然后决定，还要不要继续。", "team-before-56")
	normal("team-before-56", NARRATION, "你没有告诉她们你最害怕的事：不是四个人中有人落选，而是她们会因为落选互相恨，也会因为被选中而无法原谅自己。", "team-before-choice")
	option("team-before-choice", "名额有限的选拔前，你想强调什么？", listOf(
		"无论谁进，你们都不欠彼此一个道歉。" to "team-before-choice-a",
		"把能控制的做到极致，剩下的交给那天。" to "team-before-choice-b"
	))
	normal("team-before-choice-a", WYJ, "记住一件事：无论最后谁进，你们都不欠彼此一个道歉。", "team-before-57")
	normal("team-before-choice-b", WYJ, "把你们能控制的部分做到极致，剩下的，就交给比赛那一天。", "team-before-57")
	normal("team-before-57", WYJ, "从今天开始，不再问谁应该进。我们只问，每个人还能把什么做得更好。", "team-before-58")
	normal("team-before-58", LZN, "那我先问一个。老师，下一套题能不能别这么难？", "team-before-59")
	normal("team-before-59", WYJ, "不能。", "team-before-60")
	normal("team-before-60", LZN, "我就知道！", "team-before-61")
	normal("team-before-61", NARRATION, "她终于又开始说话。笑声并没有让名额变多，也没有让选拔变得公平，却让四个人在名单到来之前，仍然坐在同一盏灯下。", "team-before-62")
	normal("team-before-62", NARRATION, "而你知道，真正残酷的不是有人会输。是无论结果如何，所有人都会带着这场竞争留下的痕迹继续长大。", null)
}

val BeforeNoiScene = PlotTree.plotTree {
	entry("noi-before-1")
	normal("noi-before-1", NARRATION, "省队集训的最后一个晚上，宿舍楼的灯已经熄了一半。你们五个人坐在训练室里，屏幕上的提交记录像一串越来越短的呼吸。", "noi-before-2")
	normal("noi-before-2", WYM, "老师，我今天一道题都没有独立做出来。", "noi-before-3")
	normal("noi-before-3", WYJ, "今天训练结束了。", "noi-before-4")
	normal("noi-before-4", WYM, "可别人还在做。", "noi-before-5")
	normal("noi-before-5", WYJ, "别人不是你的时间。", "noi-before-6")
	normal("noi-before-6", WYM, "可是 NOI 是不是只看谁能在别人还没做出来的时候做出来？", "noi-before-7")
	normal("noi-before-7", WYJ, "是。", "noi-before-8")
	normal("noi-before-8", WYM, "那我是不是不应该在这里？", "noi-before-9")
	normal("noi-before-9", NARRATION, "你没有立刻回答。她的白色长发落在肩前，红色眼睛里没有平时的困意，只剩下一种被长期追赶后近乎透明的疲惫。", "noi-before-10")
	normal("noi-before-10", WYJ, "你应该不应该在这里，不由今天一套题决定。", "noi-before-11")
	normal("noi-before-11", WYM, "可名单会决定。", "noi-before-12")
	normal("noi-before-12", WYJ, "名单会决定你能不能进入下一场比赛，不会决定你有没有资格拥有今天坐在这里的五年。", "noi-before-13")
	normal("noi-before-13", LZN, "五年听起来好久。", "noi-before-14")
	normal("noi-before-14", WYJ, "因为你们确实走了很久。", "noi-before-15")
	normal("noi-before-15", LZN, "我有时候只记得自己输了多少次。", "noi-before-16")
	normal("noi-before-16", WYJ, "那是因为输会留下很大的声音。可你也该记得，你曾经在最紧张的时候没有乱改代码，曾经在排名掉下去以后第二天仍然打开电脑，曾经在想放弃的时候把题面重新读了一遍。", "noi-before-17")
	normal("noi-before-17", LZN, "这些也算吗？", "noi-before-18")
	normal("noi-before-18", WYJ, "如果不算，那人只能靠奖牌证明自己活过。", "noi-before-19")
	normal("noi-before-19", ZHC, "我最害怕的不是输。", "noi-before-20")
	normal("noi-before-20", WYJ, "是什么？", "noi-before-21")
	normal("noi-before-21", ZHC, "是我们一起走到这里，最后却不能一起走进去。", "noi-before-22")
	normal("noi-before-22", NARRATION, "朱皓辰看着桌上四本已经磨旧的错题本。它们的封面颜色不同，边角却都留下了同样的折痕。", "noi-before-23")
	normal("noi-before-23", LJD, "一起走到这里，本身已经是很低概率的事情。", "noi-before-24")
	normal("noi-before-24", LZN, "你又开始算概率了。", "noi-before-25")
	normal("noi-before-25", LJD, "因为如果不算，我不知道该怎么面对可能的分开。", "noi-before-26")
	normal("noi-before-26", WYJ, "你们不必把离开解释成背叛。竞赛会把人分开，学校会把人分开，生活也会把人分开。", "noi-before-27")
	normal("noi-before-27", LJD, "可我们可以不把彼此弄丢。", "noi-before-28")
	normal("noi-before-28", WYJ, "可以。但这需要比做题更长的时间。", "noi-before-29")
	normal("noi-before-29", WYM, "如果以后大家都不做竞赛了呢？", "noi-before-30")
	normal("noi-before-30", WYJ, "那也不代表你们这几年白走。你们学会了如何面对不会的东西，如何在失败后继续，如何看见一个比自己强的人却不立刻否定自己。", "noi-before-31")
	normal("noi-before-31", WYJ, "这些不会写在榜单上，但会跟着你们走得比竞赛更远。", "noi-before-32")
	normal("noi-before-32", LZN, "老师，你说得像明天以后我们就再也见不到了。", "noi-before-33")
	normal("noi-before-33", WYJ, "我只是知道，人生里很多最后一面，发生的时候并没有人知道那是最后一面。", "noi-before-34")
	normal("noi-before-34", NARRATION, "这句话落下以后，没有人再说话。训练室的空调发出低沉的声音，像很远的地方有一列火车正在经过。", "noi-before-35")
	normal("noi-before-35", WYJ, "所以今晚不要把明天想成审判。它只是一场比赛。重要，但不是你们全部的人生。", "noi-before-36")
	normal("noi-before-36", LJD, "如果我明天拿到第一，我会先回头看她们。", "noi-before-37")
	normal("noi-before-37", LZN, "不许回头。你回头我会紧张。", "noi-before-38")
	normal("noi-before-38", LJD, "那我就不回头。但我会记得你们坐在哪里。", "noi-before-39")
	normal("noi-before-39", ZHC, "我会记得灯。", "noi-before-40")
	normal("noi-before-40", WYM, "我会记得年糕。", "noi-before-41")
	normal("noi-before-41", LZN, "你怎么什么都能想到年糕？", "noi-before-42")
	normal("noi-before-42", WYM, "因为它不会问我排第几。", "noi-before-43")
	normal("noi-before-43", NARRATION, "刘子诺笑了，可笑声只持续了很短的一会儿。她低下头，悄悄把眼睛擦干。", "noi-before-44")
	normal("noi-before-44", LZN, "老师，如果明天我没有做好，你会不会觉得我们走了这么久很可惜？", "noi-before-45")
	normal("noi-before-45", WYJ, "我会觉得可惜。但可惜不是责备。", "noi-before-46")
	normal("noi-before-46", LZN, "那是什么？", "noi-before-47")
	normal("noi-before-47", WYJ, "是我知道一段很珍贵的时间结束了，却仍然愿意承认它曾经发生过。", "noi-before-48")
	normal("noi-before-48", NARRATION, "你看着她们，忽然想起最初那间合肥教室。吴一鸣还在打瞌睡，刘子诺还在大声说话，朱皓辰还不愿意主动开口，李佳迪还把自己藏在‘最强’两个字后面。", "noi-before-49")
	normal("noi-before-49", WYJ, "明天不需要证明你们配不配走到这里。你们已经走到了。明天只需要把会做的做完，把不会的想清楚，然后在时间结束时，接受那张纸。", "noi-before-choice")
	option("noi-before-choice", "NOI 前夜，你把最后一句话留给谁的心情？", listOf(
		"就当作一场普通的周日模拟赛。" to "noi-before-choice-a",
		"记住这盏灯，然后走进考场。" to "noi-before-choice-b"
	))
	normal("noi-before-choice-a", WYJ, "把明天当作一场普通的周日模拟赛。你们已经打过太多次，多这一次不多。", "noi-before-50")
	normal("noi-before-choice-b", WYJ, "记住今晚这盏灯，记住彼此坐在哪里。然后一个人走进考场，也不会觉得孤单。", "noi-before-50")
	normal("noi-before-50", ZHC, "接受结果。", "noi-before-51")
	normal("noi-before-51", WYJ, "接受结果，但不要把自己交给结果。", "noi-before-52")
	normal("noi-before-52", NARRATION, "凌晨一点，四个人终于收起电脑。没有人说‘明天一定成功’，因为她们已经知道这句话太重，也太脆弱。", "noi-before-53")
	normal("noi-before-53", WYM, "老师，明天结束以后，我们还会一起吃饭吗？", "noi-before-54")
	normal("noi-before-54", WYJ, "会。无论名单上有什么。", "noi-before-55")
	normal("noi-before-55", LZN, "那就好。我要吃很多。", "noi-before-56")
	normal("noi-before-56", LJD, "你平时也吃很多。", "noi-before-57")
	normal("noi-before-57", LZN, "明天可能是最后一顿，当然要多吃一点。", "noi-before-57a")
	// —— 回收 LznMidBondScene 里那句没说完的话 ——
	normal("noi-before-57a", NARRATION, "收拾电脑时，刘子诺磨蹭到最后一个。等另外三人先走出门，她才回过头，粉色的短发在门口的灯下显得有点软。", "noi-before-57b")
	normal("noi-before-57b", LZN, "老师，有句话我很久以前想说，说了一半就跑了。", "noi-before-57c")
	normal("noi-before-57c", WYJ, "我记得。你说，你好像不只是想赢给我看。", "noi-before-57d")
	normal("noi-before-57d", LZN, "你居然还记得……那我今天说完：我不只是想赢给你看，是想让你知道，遇到你这件事，本身就已经值得了。不管明天名单上有没有我。", "noi-before-57e")
	normal("noi-before-57e", WYJ, "……这句话，我也会记很久。快去追她们，别让她们等。", "noi-before-57f")
	normal("noi-before-57f", NARRATION, "刘子诺用力点了点头，转身跑进楼道。她没有再回头，可你看见她的脚步比来时轻快了很多。", "noi-before-58")
	normal("noi-before-58", NARRATION, "没人纠正她‘最后一顿’这个说法。因为每个人都明白，有些日子终究会结束，而真正让人难过的不是结束本身，是结束以后仍然会想起那盏灯。", "noi-before-59")
	normal("noi-before-59", WYJ, "走吧。明天见。", "noi-before-60")
	normal("noi-before-60", NARRATION, "四个女孩走出训练室。你最后关掉屏幕，提交记录停在一行普通的‘Accepted’上。你忽然觉得，这个词从来没有像今晚这样沉重。", null)
}
