package org.example.project.plots

import org.example.project.plotsFormat.Characters.*
import org.example.project.plotsFormat.PlotTree

val WymRelationshipScene = PlotTree.plotTree {
	entry("wym-r-1")
	// 吴一鸣的专属场景刻意最散漫、停顿最多：话题会跑偏到年糕，句子会被困意打断，节奏是最慢的。
	normal("wym-r-1", NARRATION, "吴一鸣的专属课结束得很晚。窗外的路灯隔着玻璃落进来，像一格一格没有写完的代码。", "wym-r-2")
	normal("wym-r-2", WYM, "老师，我是不是总是最后一个？", "wym-r-3")
	normal("wym-r-3", WYJ, "最后一个到达，不等于永远到不了。", "wym-r-4")
	normal("wym-r-4", WYM, "可是大家都已经走了很远。我刚刚学会一个东西，他们又开始学下一个。", "wym-r-5")
	normal("wym-r-5", WYJ, "那就不要用别人的下一站，否定自己的这一站。", "wym-r-6")
	normal("wym-r-6", NARRATION, "她低头摸着书包上的猫咪挂件，红色的眼睛困得发亮。她没有立刻接话，教室里安静了好一会儿，只剩下空调低低的声音。", "wym-r-7")
	normal("wym-r-7", WYM, "……老师，你有没有养过猫？", "wym-r-8")
	normal("wym-r-8", WYJ, "没有。怎么突然问这个？", "wym-r-9")
	normal("wym-r-9", WYM, "没什么。就是……想到年糕了。", "wym-r-10")
	normal("wym-r-10", WYM, "年糕睡觉的时候，我有时候会觉得它什么都没有做。可是它醒来以后，还是会跑过来蹭我。", "wym-r-11")
	normal("wym-r-11", WYJ, "因为被喜欢不需要先交出一张满分成绩单。", "wym-r-12")
	normal("wym-r-12", NARRATION, "她想笑，却先打了个小小的哈欠。白色的长发滑到脸颊边，她慢半拍地把它拨开。", "wym-r-13")
	normal("wym-r-13", WYM, "老师，我刚才想说什么来着……", "wym-r-14")
	normal("wym-r-14", WYJ, "你在问，就算学得很慢，我会不会也让你继续来。", "wym-r-15")
	normal("wym-r-15", WYM, "对。就是这个。", "wym-r-16")
	normal("wym-r-16", WYJ, "只要你来是因为你愿意，而不是因为你害怕让我失望。", "wym-r-17")
	normal("wym-r-17", WYM, "我以前很怕。怕你觉得我浪费了你的时间。", "wym-r-18")
	normal("wym-r-18", WYJ, "你没有浪费我的时间。你让我知道，教学不是把最快的人送得更快，而是让一个差点停下来的人，重新找到自己的速度。", "wym-r-19")
	normal("wym-r-19", NARRATION, "她很久没有说话。窗外有车经过，车灯从她白色的长发上滑过去。你以为她睡着了，可她的手指还在挂件上轻轻地动。", "wym-r-20")
	normal("wym-r-20", WYM, "……唔。", "wym-r-21")
	normal("wym-r-21", NARRATION, "那声音又轻又含糊，像是回应，又像只是睡意里漏出来的一点动静。你没有追问，只是等着。", "wym-r-22")
	normal("wym-r-22", NARRATION, "过了很久，久到你以为她不会再开口了，她才把脸贴在凉凉的桌面上，声音闷闷地传过来。", "wym-r-23")
	normal("wym-r-23", WYM, "……那我今天可以不做最后一道题吗？", "wym-r-24")
	normal("wym-r-24", WYJ, "可以。把前面已经做对的题整理好。", "wym-r-25")
	normal("wym-r-25", WYM, "老师，你是不是很会照顾人？", "wym-r-26")
	normal("wym-r-26", WYJ, "不是。我只是也曾经希望有人在我做错的时候，没有立刻问我为什么还不够好。", "wym-r-27")
	normal("wym-r-27", WYM, "那我以后也会记得。等我学会了，就去照顾还不会的人。", "wym-r-28")
	normal("wym-r-28", WYJ, "好。那比成为 NOI Au 更重要。", "wym-r-29")
	normal("wym-r-29", WYM, "……还有年糕。也要照顾年糕。", "wym-r-30")
	normal("wym-r-30", NARRATION, "她终于把错题本合上，动作很慢，慢到像怕吵醒什么。她没有趴下睡着，只是很慢地走出教室，一步，一停，像是在确认每一步都属于自己。", null)
}

val LznRelationshipScene = PlotTree.plotTree {
	entry("lzn-r-1")
	normal("lzn-r-1", NARRATION, "刘子诺的成绩又一次掉了下来。她把成绩单折成很小的一块，塞进衬衫口袋，整节课都没有说话。", "lzn-r-2")
	normal("lzn-r-2", WYJ, "你今天很安静。", "lzn-r-3")
	normal("lzn-r-3", LZN, "我怕我一说话，就会哭。那样太丢脸了。", "lzn-r-4")
	normal("lzn-r-4", WYJ, "哭不是比赛违规。", "lzn-r-5")
	normal("lzn-r-5", LZN, "可我明明已经知道怎么做了。我知道检查很重要，知道不能被一道题拖住，知道看见李佳迪的名字在前面也不能急。可到了比赛里，我还是会变成另一个人。", "lzn-r-6")
	normal("lzn-r-6", WYJ, "那不是另一个人。那是紧张的你。", "lzn-r-7")
	normal("lzn-r-7", LZN, "我不喜欢她。她总是把我辛苦练会的东西弄坏。", "lzn-r-8")
	normal("lzn-r-8", WYJ, "可她也一次次把你送回训练桌前。", "lzn-r-9")
	normal("lzn-r-9", NARRATION, "她盯着桌面，眼泪终于掉下来。她很快用手背擦掉，像是在删除一条不该出现的错误信息。", "lzn-r-10")
	normal("lzn-r-10", LZN, "老师，你是不是也会对我失望？", "lzn-r-11")
	normal("lzn-r-11", WYJ, "我会对你的某些选择失望，比如明明知道要检查却故意不检查。但我不会因为一次结果，就对你这个人失望。", "lzn-r-12")
	normal("lzn-r-12", LZN, "这有什么区别？", "lzn-r-13")
	normal("lzn-r-13", WYJ, "区别是，前者可以改，后者不该由一张成绩单决定。", "lzn-r-14")
	normal("lzn-r-14", LZN, "我有时候真的很羡慕李佳迪。她好像不用害怕，就能把题做出来。", "lzn-r-15")
	normal("lzn-r-15", WYJ, "你看见的是她交卷后的样子。你没有看见她在交卷前删掉了多少次代码，也没有看见她害怕自己不再是第一。", "lzn-r-16")
	normal("lzn-r-16", LZN, "那朱皓辰呢？她好像什么都不怕。", "lzn-r-17")
	normal("lzn-r-17", WYJ, "她只是把害怕藏得比你深。你们不是在和彼此比赛，你们是在学着不被自己的恐惧牵着走。", "lzn-r-18")
	normal("lzn-r-18", LZN, "老师，我可以继续当一个不稳定的人吗？", "lzn-r-19")
	normal("lzn-r-19", WYJ, "可以。但你不能把不稳定当成判决书。它只是你现在需要训练的一部分。", "lzn-r-20")
	normal("lzn-r-20", LZN, "那我下次还会回来。就算我又考砸了，也回来。", "lzn-r-21")
	normal("lzn-r-21", WYJ, "我会给你留位置。", "lzn-r-22")
	normal("lzn-r-22", NARRATION, "她终于哭出声来，却又很快笑了一下。那张被折得发皱的成绩单没有被丢掉，她把它重新展开，放进了错题本里。", null)
}

val ZhcRelationshipScene = PlotTree.plotTree {
	entry("zhc-r-1")
	normal("zhc-r-1", NARRATION, "朱皓辰很少主动留下。那天她却坐到所有人离开，教室的灯只剩下一盏。", "zhc-r-2")
	normal("zhc-r-2", WYJ, "有事想说？", "zhc-r-3")
	normal("zhc-r-3", ZHC, "没有。只是今天不想那么快回家。", "zhc-r-4")
	normal("zhc-r-4", WYJ, "那就坐一会儿。", "zhc-r-5")
	normal("zhc-r-5", NARRATION, "你没有追问。朱皓辰把错题本摊开，却很久没有翻页。", "zhc-r-6")
	normal("zhc-r-6", ZHC, "大家都说我很稳。老师也这么说。", "zhc-r-7")
	normal("zhc-r-7", WYJ, "你确实很稳。", "zhc-r-8")
	normal("zhc-r-8", ZHC, "可我不喜欢这个词。有时候它像一句要求：既然你很稳，就不能崩溃，不能害怕，不能在考场上不知道怎么办。", "zhc-r-9")
	normal("zhc-r-9", WYJ, "稳定不是不许倒下，是倒下之后知道怎么把自己扶起来。", "zhc-r-10")
	normal("zhc-r-10", ZHC, "如果我也想有人扶呢？", "zhc-r-11")
	normal("zhc-r-11", NARRATION, "她的声音很轻，轻到像只是随口问了一句。可你知道，她可能已经在心里问过很多年。", "zhc-r-12")
	normal("zhc-r-12", WYJ, "那就说出来。你不需要永远做那个替别人整理桌面的人。", "zhc-r-13")
	normal("zhc-r-13", ZHC, "我不太会说。", "zhc-r-14")
	normal("zhc-r-14", WYJ, "可以慢慢说。编程也是这样，先把问题拆小。", "zhc-r-15")
	normal("zhc-r-15", ZHC, "第一部分是，我害怕有一天大家都不需要我。第二部分是，我害怕即使大家需要我，也只是因为我不会出错。", "zhc-r-16")
	normal("zhc-r-16", WYJ, "你不是因为不会出错才值得被需要。你能听见别人没有说出口的话，这也是能力。", "zhc-r-17")
	normal("zhc-r-17", ZHC, "那如果我有一天不想做题了呢？", "zhc-r-18")
	normal("zhc-r-18", WYJ, "可以休息。只要那是你的决定，不是因为你认为自己没有资格继续。", "zhc-r-19")
	normal("zhc-r-19", ZHC, "王老师，你总是把选择还给我们。", "zhc-r-20")
	normal("zhc-r-20", WYJ, "因为你们迟早要独自面对名单。我希望那时候，你们至少知道自己不是被别人推到那里去的。", "zhc-r-21")
	normal("zhc-r-21", ZHC, "今天我想留下，是我自己的选择。", "zhc-r-22")
	normal("zhc-r-22", WYJ, "我知道。", "zhc-r-23")
	normal("zhc-r-23", NARRATION, "她合上错题本。那天她没有写下新的分类，也没有整理任何人的资料，只安静地坐到了灯光熄灭。", null)
}

val LjdRelationshipScene = PlotTree.plotTree {
	entry("ljd-r-1")
	// 李佳迪的专属场景刻意最短、最冷：她把话压到最少，只在最要紧处露出一次裂缝。
	normal("ljd-r-1", NARRATION, "李佳迪把一份训练计划放在你面前。纸上的字一如既往地整齐，只有最后一行被反复划掉。", "ljd-r-2")
	normal("ljd-r-2", WYJ, "最后一行写了什么？", "ljd-r-3")
	normal("ljd-r-3", LJD, "‘我想休息。’", "ljd-r-4")
	normal("ljd-r-4", WYJ, "为什么划掉？", "ljd-r-5")
	normal("ljd-r-5", LJD, "因为这看起来不像李佳迪会说的话。", "ljd-r-6")
	normal("ljd-r-6", WYJ, "李佳迪是谁？", "ljd-r-7")
	normal("ljd-r-7", LJD, "四个人里最强的那个。不能在别人之前停下来。", "ljd-r-8")
	normal("ljd-r-8", WYJ, "那是别人写给你的简介，不是你本人。", "ljd-r-9")
	normal("ljd-r-9", LJD, "可他们没说错。我停下来，就会有人超过我。", "ljd-r-10")
	normal("ljd-r-10", WYJ, "被超过不是犯罪。", "ljd-r-11")
	normal("ljd-r-11", LJD, "对你不是。对我，像是证明我没那么好。", "ljd-r-12")
	normal("ljd-r-12", NARRATION, "她说这句话时没有哭，甚至没有明显的表情。正因为如此，你听见了那种已经持续很久的疲惫。", "ljd-r-13")
	normal("ljd-r-13", WYJ, "我拿过 NOI Ag，也拿过 ICPC Final Au。可我仍然会在比赛里失去状态，仍然会在输掉以后怀疑自己。", "ljd-r-14")
	normal("ljd-r-14", LJD, "所以你也没有答案。", "ljd-r-15")
	normal("ljd-r-15", WYJ, "没有。可没有答案，不等于不能继续问。", "ljd-r-16")
	normal("ljd-r-16", LJD, "我不想永远只做第一。", "ljd-r-17")
	normal("ljd-r-17", WYJ, "那你想做什么？", "ljd-r-18")
	normal("ljd-r-18", LJD, "一个即使被超过，也愿意把题做完的人。", "ljd-r-19")
	normal("ljd-r-19", WYJ, "这是你的时间。休息不需要我允许。", "ljd-r-20")
	normal("ljd-r-20", NARRATION, "她把最后一行重新写进计划，没有再划掉。那不是退让，而是她第一次把自己也算进了未来。她收好纸，起身，只留下一句‘明天继续’，便走进了走廊的灯里。", null)
}
